import { readFileSync } from "node:fs";
import { join } from "node:path";

import { ImageZoom } from "fumadocs-ui/components/image-zoom";

/*
 * Screenshots are generated by `bun run screenshots` in the repository root,
 * which writes a light and a dark capture of every shot to
 * public/screenshots/<name>.<theme>.webp.
 */
const SCREENSHOTS = join(process.cwd(), "public", "screenshots");

/** Width and height from a WebP header (lossy, lossless or extended). */
const FOURTEEN_BITS = 2 ** 14;
const webpSize = (file: Buffer) => {
  const chunk = file.toString("ascii", 12, 16);
  if (chunk === "VP8 ") {
    return {
      height: file.readUInt16LE(28) % FOURTEEN_BITS,
      width: file.readUInt16LE(26) % FOURTEEN_BITS,
    };
  }
  if (chunk === "VP8L") {
    const bits = file.readUInt32LE(21);
    return {
      height: (Math.floor(bits / FOURTEEN_BITS) % FOURTEEN_BITS) + 1,
      width: (bits % FOURTEEN_BITS) + 1,
    };
  }
  if (chunk === "VP8X") {
    return {
      height: file.readUIntLE(27, 3) + 1,
      width: file.readUIntLE(24, 3) + 1,
    };
  }
  throw new Error(`Unrecognised WebP chunk "${chunk}"`);
};

const load = (name: string, theme: "light" | "dark") => {
  const file = `${name}.${theme}.webp`;
  let data: Buffer;
  try {
    data = readFileSync(join(SCREENSHOTS, file));
  } catch (error) {
    throw new Error(
      `Screenshot "${file}" is missing; add the shot and run \`bun run screenshots\`.`,
      { cause: error }
    );
  }
  // Captured at 2x, so show them at their CSS pixel size.
  const { width, height } = webpSize(data);
  return {
    height: Math.round(height / 2),
    src: `/screenshots/${file}`,
    width: Math.round(width / 2),
  };
};

// Full-window shots would otherwise blend into the page.
const frame = "rounded-lg border";

export function Screenshot({
  name,
  alt,
  caption,
}: Readonly<{ name: string; alt: string; caption?: string }>) {
  if (!alt.trim()) {
    throw new Error(`Screenshot "${name}" needs alt text.`);
  }
  const light = load(name, "light");
  const dark = load(name, "dark");

  return (
    <figure>
      <div className="dark:hidden">
        <ImageZoom alt={alt} className={frame} {...light} />
      </div>
      <div className="hidden dark:block">
        <ImageZoom alt={alt} className={frame} {...dark} />
      </div>
      {caption ? (
        <figcaption className="text-center">{caption}</figcaption>
      ) : null}
    </figure>
  );
}
