INSERT INTO airline (name, icao, iata)
SELECT *
FROM (VALUES ('21 Air', 'CSB', '2I'),
             ('2Excel Aviation', 'BRO', null),
             ('40-Mile Air', 'MLA', 'Q5'),
             ('9 Air', 'JYH', 'AQ'),
             ('ABS Jets', 'ABP', null),
             ('ABX Air', 'ABX', 'GB'),
             ('Advanced Air', 'WSN', 'AN'),
             ('Aer Lingus', 'EIN', 'EI'),
             ('AerCaribe', 'ACL', 'JK'),
             ('Aero', 'NIG', 'N2'),
             ('Aero Charter', 'GLT', null),
             ('Aero Dili', 'DTL', '8G'),
             ('Aero Guernsey', 'AEO', null),
             ('Aero Mongolia', 'MNG', 'M0'),
             ('Aero Sotravia', 'ASR', null),
             ('Aero-Beta Flight Training', 'ABA', null),
             ('Aeroavila Transortes Aereos', 'KKA', null),
             ('AeroGuard Flight Training Center', 'ASI', null),
             ('Aerojet Tomza', 'EZI', null),
             ('Aerolineas Ejecutivas', 'LET', null),
             ('Aerolink Uganda', 'XAU', 'A8'),
             ('Aeromas', 'MSM', null),
             ('Aeromexico Connect', 'SLI', '5D'),
             ('Aeronaves TSM', 'VTM', null),
             ('Aeropyrenees', 'EAP', null),
             ('Aeroservicios Avila', 'VEA', null),
             ('Aerostan', 'BSC', 'KW'),
             ('Aerosul Linhas Aereas', 'ASO', null),
             ('Aerotours', 'ATU', null),
             ('AeroUnion', 'TNO', '6R'),
             ('Aerovis Airlines', 'VIZ', null),
             ('Aerus', 'RFD', 'ZV'),
             ('Africa Airlines', 'AAT', null),
             ('Africa World Airlines', 'AFW', 'AW'),
             ('Afrijet', 'ABS', 'J7'),
             ('Aims Community College', 'RTY', null),
             ('Air Adelphi', 'MUS', null),
             ('Air Algerie', 'DAH', 'AH'),
             ('Air Alsie', 'MMD', '6I'),
             ('Air Antilles', 'KES', '4I'),
             ('Air Arabia Abu Dhabi', 'ADY', '3L'),
             ('Air Arabia Maroc', 'MAC', '3O'),
             ('Air Astra', 'AWA', '2A'),
             ('Air Atlanta Icelandic', 'ABD', 'CC'),
             ('Air Baltic', 'BTI', 'BT'),
             ('Air Bohemia', 'BOH', null),
             ('Air Botswana', 'BOT', 'BP'),
             ('Air Busan', 'ABL', 'BX'),
             ('Air Caledonie', 'TPC', 'TY'),
             ('Air Canada Rouge', 'ROU', 'RV'),
             ('Air Caraïbes Atlantique', 'CAJ', null),
             ('Air Cargo Carriers', 'SNC', '2Q'),
             ('Air Century', 'CEY', 'Y2'),
             ('Air Charity Network', 'NGF', null),
             ('Air Charter Scotland Europe', 'SCO', null),
             ('Air Chathams', 'CVA', '3C'),
             ('Air China Cargo', 'CAO', null),
             ('Air Class', 'QCL', null),
             ('Air Corsica', 'CCM', 'XK'),
             ('Air Creebec', 'CRQ', 'YN'),
             ('Air Dilijans', 'NGT', 'RM'),
             ('Air Do', 'ADO', 'HD'),
             ('Air Eagle', 'EPE', null),
             ('Air Europa Express', 'OVA', 'X5'),
             ('Air Falcon', 'FPK', 'FS'),
             ('Air France', 'AFR', 'AF'),
             ('Air Ghana', 'GHN', null),
             ('Air Guilin', 'CGH', 'GT'),
             ('Air Hong Kong', 'AHK', 'LD'),
             ('Air Incheon', 'AIH', 'KJ'),
             ('Air India Express', 'AXB', 'IX'),
             ('Air Japan', 'AJX', 'NQ'),
             ('Air Kiribati', 'AKL', 'IK'),
             ('Air Leisure', 'ALD', 'AL'),
             ('Air Libya', 'TLR', '7I'),
             ('Air Macau', 'AMU', 'NX'),
             ('Air Madagascar', 'MDG', 'MD'),
             ('Air Mauritius', 'MAU', 'MK'),
             ('Air Methods', 'LIF', null),
             ('Air Montenegro', 'MNE', '4O'),
             ('Air New Zealand', 'ANZ', 'NZ'),
             ('Air North', 'ANT', '4N'),
             ('Air Nunavut', 'BFF', null),
             ('Air Panama', 'PST', '7P'),
             ('Air Premia', 'APZ', 'YP'),
             ('Air Safaris', 'SRI', null),
             ('Air Samarkand', 'UZS', '9S'),
             ('Air Seoul', 'ASV', 'RS'),
             ('Air Sphinx', 'ASD', null),
             ('Air Sunshine', 'RSI', null),
             ('Air Tahiti Nui', 'THT', 'TN'),
             ('Air Taxi & Charter International', 'IBJ', null),
             ('Air Thanlwin', 'RTL', 'ST'),
             ('Air Transat', 'TSC', 'TS'),
             ('Air Transport International', 'ATN', '8C'),
             ('Air Urga', 'URG', '3N'),
             ('Air Volta', 'VLB', null),
             ('Air X Charter', 'AXY', null),
             ('Air-Glaciers', 'AGV', null),
             ('Air1Air', 'INA', null),
             ('AirACT', 'RUN', '9T'),
             ('AirAsia Cambodia', 'KTC', 'KT'),
             ('AirBlue', 'ABQ', 'PA'),
             ('Airbus', 'AIB', null),
             ('Airbus Transport International', 'BGA', '4Y'),
             ('AirConnect', 'KON', 'KS'),
             ('Aireon Canada', 'AEN', null),
             ('AirExplore', 'AXE', 'ED'),
             ('AirGO Private Airline', 'XGO', null),
             ('AirJet', 'MBC', null),
             ('Airlec Air Espace', 'ARL', null),
             ('Airlift International', 'AIR', null),
             ('Airlink', 'LNK', '4Z'),
             ('Airmax', 'MMX', null),
             ('Airnorth', 'ANO', 'TL'),
             ('AirPink', 'PNK', null),
             ('AirSF Flight Services', 'XSN', null),
             ('AirSial', 'SIF', 'PF'),
             ('AirSprint', 'ASP', null),
             ('AirSWIFT', 'ATX', 'T6'),
             ('Airtask', 'DCT', null),
             ('Airvan Kenya', 'AKV', null),
             ('Airwork', 'AWK', null),
             ('Aitheras Aviation Group', 'PXG', null),
             ('AJet', 'TKJ', 'VF'),
             ('Al-Atheer Aviation', 'ATE', null),
             ('Alante Air Charter', 'SVL', null),
             ('Alaska Central Express', 'AER', 'KO'),
             ('Albatros Airlines', 'GAL', 'G0'),
             ('Albinati Aviation', 'ULC', null),
             ('Alexjets San Marino', 'AXJ', null),
             ('Algonquin Airlink', 'FSY', null),
             ('AlisCargo Airlines', 'LSI', 'CP'),
             ('ALK Airlines', 'VBB', null),
             ('Alkan Air', 'AKN', null),
             ('Allegiant Air', 'AAY', 'G4'),
             ('Alliance Airlines', 'UTY', 'QQ'),
             ('Allied Air', 'AJK', '4W'),
             ('Aloha Air Cargo', 'AAH', 'KH'),
             ('Alpha Aviation', 'AAO', null),
             ('AlphaSky', 'JAG', 'AS'),
             ('Alpine Air Express', 'AIP', '5A'),
             ('Alrosa', 'DRU', '6R'),
             ('Altair Airlines', 'AQL', null),
             ('Amakusa Airlines', 'AHX', 'MZ'),
             ('AMC Aviation', 'AMQ', null),
             ('Amelia International', 'AEH', 'NL'),
             ('American Airlines', 'AAL', 'AA'),
             ('American Jet International', 'SCM', null),
             ('Amerijet International', 'AJT', 'M6'),
             ('AMREF Flying Doctors', 'FDS', null),
             ('ANA Wings', 'AKX', 'EH'),
             ('Anderson Air', 'ADS', null),
             ('Angara Airlines', 'AGU', null),
             ('Animawings', 'AWG', 'A2'),
             ('APG Airlines', 'RIV', 'GP'),
             ('Arc en Ciel', 'JMS', null),
             ('Arcus Air', 'AZE', null),
             ('Ariana Afghan Airlines', 'AFG', 'FG'),
             ('Arik Air', 'ARA', 'W3'),
             ('Arkia Israeli Airlines', 'AIZ', 'IZ'),
             ('Armenian Airlines', 'AAG', 'JI'),
             ('ASAS Linhas Aereas', 'CEU', null),
             ('ASG Business Aviation', 'ESW', null),
             ('Asia Pacific Airlines', 'MGE', 'P9'),
             ('Asia Union Airlines', 'AUV', '7Q'),
             ('Asian Express General Aviation Wuxi', 'WUA', null),
             ('Asky Airlines', 'SKK', 'KP'),
             ('ASL Airlines Australia', 'PHA', 'PH'),
             ('ASL Airlines France', 'FPO', '5O'),
             ('Asta Linhas Aereas', 'SUL', '0A'),
             ('Astonjet Malta', 'AJD', null),
             ('ATA Airlines', 'TBZ', 'I3'),
             ('Atlantic Airways', 'FLI', 'RC'),
             ('Atlantic Jets', 'AJG', null),
             ('Atlas Air Service', 'ATL', null),
             ('ATR', 'EVX', null),
             ('Atsa Airlines', 'AMP', '4A'),
             ('Auric Air', 'AUK', 'UI'),
             ('Aurora', 'SHU', 'HZ'),
             ('Australia - Royal Australian Air Force', 'ASY', null),
             ('Austrian Airlines', 'AUA', 'OS'),
             ('AVA Airlines', 'AXV', null),
             ('Avanti Air', 'ATV', null),
             ('Avcon Jet', 'AOJ', null),
             ('Avcon Jet San Marino', 'VAJ', null),
             ('Avia Traffic', 'AVJ', 'YK'),
             ('Avianca', 'AVA', 'AV'),
             ('Avianca Costa Rica', 'LRC', 'LR'),
             ('Avianca El Salvador', 'TAI', 'TA'),
             ('Avianca Guatemala', 'GUG', 'GU'),
             ('Aviastar-TU', 'TUP', '4B'),
             ('Aviation Horizons', 'HZS', 'ZS'),
             ('Aviatsa', 'VVT', null),
             ('Avincis Aviation Italia', 'ELH', null),
             ('Avincis Aviation Sweden', 'DFL', null),
             ('Avion Express Brasil', 'AEB', null),
             ('Avionord', 'VND', null),
             ('Aviostart', 'VSR', null),
             ('Awesome Cargo', 'WIN', 'A7'),
             ('Axis Aviation San Marino', 'AXS', null),
             ('Azimut', 'MOM', null),
             ('Azman Air', 'AZM', 'ZU'),
             ('Aztec Airways', 'AZY', 'AJ'),
             ('Azul Conecta', 'ACN', '2F'),
             ('B.J. Aviation', 'JSG', null),
             ('BA Euroflyer', 'EFW', 'A0'),
             ('Babcock MCS France', 'PTH', null),
             ('Baden Aircraft Operations', 'BAO', null),
             ('BAe Systems', 'BAE', null),
             ('Bahamasair', 'BHS', 'UP'),
             ('Baker Aviation', 'KOW', null),
             ('Bangkok Airways', 'BKP', 'PG'),
             ('Bar XH Air', 'BXH', null),
             ('Bassaka Air', 'BSX', '5B'),
             ('Batik Air Malaysia', 'MXD', 'OD'),
             ('BBN Airlines Indonesia', 'BBL', '7B'),
             ('Bees Airlines', 'BES', 'E8'),
             ('Bel Air Aviation', 'BBX', null),
             ('Belgium - Air Force', 'BAF', null),
             ('Belgium - Gendarmerie', 'GDB', null),
             ('BellAir', 'TCN', null),
             ('Beond', 'BYD', 'B4'),
             ('Berjaya Air', 'BVT', 'J8'),
             ('Berniq Airways', 'BNL', 'NB'),
             ('Bestfly Aruba', 'BFY', null),
             ('Bhutan Airlines', 'BTN', 'B3'),
             ('Bighorn Airways', 'BHR', null),
             ('BinAir', 'BID', null),
             ('Binter Canarias', 'IBB', 'NT'),
             ('Blackbird Air', 'BBB', null),
             ('Blue Bird Aviation', 'BLB', null),
             ('Blue Islands', 'BCI', 'SI'),
             ('Blue Square Aviation', 'BSG', null),
             ('Bluebird Aviation', 'BBZ', null),
             ('BlueSky Aviation', 'SBK', null),
             ('Boliviana de Aviacion', 'BOV', 'OB'),
             ('Bookajet', 'BOO', null),
             ('BRA', 'BRX', 'TF'),
             ('Braspress Air Cargo', 'BPC', null),
             ('Brazil - Air Force', 'BRS', null),
             ('Brazil - Navy', 'MBR', null),
             ('Bridger Aerospace', 'BGR', null),
             ('Brilliant Jet', 'TXJ', null),
             ('Bristow Nigeria', 'BHN', null),
             ('Bristow US', 'BTZ', null),
             ('British Airways Shuttle', 'SHT', null),
             ('Bromma Air Maintenance', 'CFL', null),
             ('Budapest Aircraft Service', 'BPS', 'RP'),
             ('Budget Lines', 'BGN', 'BD'),
             ('Bul Air', 'BVL', 'LB'),
             ('Bulgaria - Government', 'BGF', null),
             ('Buraq Air', 'BRQ', 'UZ'),
             ('Business Aviation Asia', 'UNA', 'UN'),
             ('Buzz', 'RYS', 'RR'),
             ('C&M Airways', 'RWG', null),
             ('Cabo Verde Airlines', 'TCV', 'VR'),
             ('CAE', 'OXF', null),
             ('Calm Air', 'CAV', 'MO'),
             ('Camair-Co', 'CRC', 'QC'),
             ('Cambodia Angkor Air', 'KHV', 'K6'),
             ('Camex Airlines', 'CMS', 'Z7'),
             ('Canadian Airways Congo', 'TWC', null),
             ('Canair', 'RSC', null),
             ('Canavia', 'CNA', null),
             ('CanWest Air', 'CWA', null),
             ('Capital Air Ambulance', 'EGL', null),
             ('Capital City Air Carriers', 'CCQ', null),
             ('CareFlight', 'CFH', null),
             ('Cargo Three', 'CTW', 'C3'),
             ('Cargolux', 'CLX', 'CV'),
             ('Caribbean Airlines', 'BWA', 'BW'),
             ('Carpatair', 'KRP', 'V3'),
             ('Caspian Airlines', 'CPN', 'RV'),
             ('Cat Aviation', 'CAZ', null),
             ('Catreus', 'VCG', null),
             ('Cayman Airways', 'CAY', 'KX'),
             ('Cebgo', 'SRQ', 'DG'),
             ('Ceiba Intercontinental', 'CEL', null),
             ('Centene Management Company', 'TMP', null),
             ('Central Airlines', 'HLF', 'I9'),
             ('Centreline', 'CLF', null),
             ('Chabahar Airlines', 'IRU', null),
             ('Chalair Aviation', 'CLG', 'CE'),
             ('Challenge Airlines BE', 'CHG', 'X7'),
             ('Cham Wings Airlines', 'SAW', null),
             ('Charter Jets', 'LTC', null),
             ('CHC Helicopter', 'HMB', null),
             ('CHC Helicopters Nigeria', 'ATQ', null),
             ('CHC International', 'GCY', null),
             ('Chervon', 'GLH', null),
             ('China - Air Force', 'CKJ', null),
             ('China Airlines', 'CAL', 'CI'),
             ('China Eastern Airlines', 'CES', 'MU'),
             ('China Postal Airlines', 'CYZ', 'CF'),
             ('China Southern Cargo', 'CSG', null),
             ('Chodang University', 'CDQ', null),
             ('Chrono Aviation', 'NDL', 'MB'),
             ('Cinnamon Air', 'CIN', 'C7'),
             ('CITIC Offshore Helicopter', 'CHC', null),
             ('Cityjet', 'BCY', 'WX'),
             ('Class Aviation', 'DUC', null),
             ('ClipperJet', 'ORO', null),
             ('CMA CGM AirCargo', 'CMA', '2C'),
             ('Cobalt Air', 'FCB', 'CO'),
             ('Colombia - Air Force', 'FAC', null),
             ('Comlux', 'CLA', null),
             ('Comlux Kazakhstan', 'KAZ', null),
             ('CommuteAir', 'UCA', 'C5'),
             ('Compass Cargo Airlines', 'ADZ', 'HQ'),
             ('Condor', 'CFG', 'DE'),
             ('Conquest Air', 'QAI', 'C4'),
             ('Contour Aviation', 'VTE', 'LF'),
             ('Copa Airlines', 'CMP', 'CM'),
             ('Corendon Airlines', 'CAI', 'XC'),
             ('Corendon Dutch Airlines', 'CND', 'CD'),
             ('Corporate Air', 'MLN', null),
             ('Corsair', 'CRL', 'SS'),
             ('Costa Rica Green Airways', 'CRG', 'GW'),
             ('Cristalux', 'AUZ', '7Z'),
             ('Croatia Airlines', 'CTN', 'OU'),
             ('Cronos Airlines Benin', 'CKL', null),
             ('Crystal Air', 'CYT', null),
             ('CSI Aviation', 'CSI', null),
             ('Cubana', 'CUB', 'CU'),
             ('Cyprus Airways', 'CYP', 'CY'),
             ('Czechia - Air Force', 'CEF', null),
             ('Daallo Airlines', 'DAO', 'D3'),
             ('Dan Air', 'DNA', 'DN'),
             ('DAS Private Jets', 'DWW', null),
             ('DAT', 'DTR', 'DX'),
             ('DB Aviation', 'DBT', null),
             ('DC Aviation', 'DCS', null),
             ('DEA Aviation', 'WKT', null),
             ('Deer Jet Beijing', 'BDJ', null),
             ('Delta State University', 'DSU', null),
             ('Denmark - Navy', 'DNY', null),
             ('Desert Jet', 'DJR', null),
             ('DesertAir Alaska', 'DAZ', null),
             ('Dexter Air Taxi', 'DXT', null),
             ('DHL Air', 'DHK', 'D0'),
             ('DHL Aviation EEMEA', 'DHX', 'ES'),
             ('Dillon Aero', 'KTY', null),
             ('Divi Divi Air', 'DVR', '3R'),
             ('Donghai Airlines', 'EPA', 'DZ'),
             ('Douniah Airlines', 'DTS', 'DH'),
             ('Draken Europe', 'FRA', null),
             ('DRF Luftrettung', 'AMB', '1I'),
             ('Druk Air', 'DRK', 'KB'),
             ('Duke Energy Business Services', 'GGW', null),
             ('E-Aviation', 'EFD', null),
             ('EADS CASA', 'AED', null),
             ('Eagle Air', 'EGU', null),
             ('Eagle Creek Aviation', 'EGC', null),
             ('East Coast Jets', 'ECJ', null),
             ('East-West Express', 'EWU', null),
             ('Eastern Air Express', 'BBQ', null),
             ('Eastern Airways', 'EZE', 'T3'),
             ('Easy Charter', 'LOL', 'RD'),
             ('easyJet Europe', 'EJU', 'EC'),
             ('EATIS', 'SRK', null),
             ('ECO Airlines', 'EKO', null),
             ('Ecuador - Air Force', 'FAE', null),
             ('EGT Jet', 'EGT', null),
             ('Egyptair', 'MSR', 'MS'),
             ('EJM Europe', 'JME', null),
             ('Elangeni', 'ELG', null),
             ('Elemental Aviation', 'MWH', null),
             ('Elilombarda', 'EOA', null),
             ('Elit''Avia International', 'EAA', null),
             ('Elitavia', 'EAV', null),
             ('Elite Air', 'ELZ', null),
             ('Elitellina', 'FGS', null),
             ('Embraer', 'EMB', null),
             ('Emerald Airlines', 'EAI', 'EA'),
             ('Emetebe', 'EMT', null),
             ('Emirates Flight Training Academy', 'EFC', null),
             ('Empire Airlines', 'CFS', 'EM'),
             ('ENAC Ecole Aviation Civile', 'NAK', null),
             ('Endeavor Air', 'EDV', '9E'),
             ('Enter Air', 'ENT', 'E4'),
             ('Epic Flight Academy', 'EPI', null),
             ('Era Helicopters', 'ERH', null),
             ('Estelar', 'ETR', 'ES'),
             ('Eswatini Air', 'SZL', 'RN'),
             ('Ethiopian Airlines', 'ETH', 'ET'),
             ('Euro Link', 'EUL', null),
             ('EuroAtlantic Airways', 'MMZ', 'YU'),
             ('Eurocopter Deutschland', 'RDF', null),
             ('European Air Transport', 'BCS', 'QY'),
             ('European Cargo', 'URO', 'SE'),
             ('European Flight Service', 'EUW', null),
             ('European SAO', 'EKT', null),
             ('Eurowings Europe', 'EWL', 'E6'),
             ('Everts Air Alaska', 'VTS', '5V'),
             ('Excellent Air', 'ECA', null),
             ('Execuflight', 'EFT', null),
             ('Execujet Scandinavia', 'VMP', null),
             ('Executive Aviation Corporation', 'SIY', null),
             ('Executive Jet Management', 'EJM', null),
             ('Express Air Cargo', 'XRC', '7A'),
             ('Exxaero', 'XRO', null),
             ('Ezy Airlines', 'EZT', null),
             ('Falcon Aviation Services', 'FVS', null),
             ('Farmingdale State University', 'FDL', null),
             ('Fastjet', 'FJW', 'FN'),
             ('FedEx', 'FDX', 'FX'),
             ('Feuerwehr-Flugdienst Niedersachsen', 'FFD', null),
             ('Fiji Link', 'FJA', null),
             ('Finland - Air Force', 'FNF', null),
             ('Finnair', 'FIN', 'AY'),
             ('Firefly', 'FFM', 'FY'),
             ('First Nation Airways', 'FRN', null),
             ('Flair Airlines', 'FLE', 'F8'),
             ('Flexflight', 'FXT', 'W2'),
             ('Flexjet Europe', 'FLJ', null),
             ('Flight Calibration Services', 'FCK', null),
             ('Flight Fast Track', 'FTT', null),
             ('Flight Training Europe', 'AYR', null),
             ('Flightline', 'FTL', null),
             ('Flightpath Charter Airways', 'KNT', null),
             ('Florida Air Cargo', 'FAS', null),
             ('Fltplan', 'DCM', null),
             ('Fly 7', 'FSF', null),
             ('Fly Air41', 'BER', null),
             ('Fly AllWays', 'EDR', '8W'),
             ('Fly Angola', 'FLA', 'EQ'),
             ('Fly Express Airlines', 'FXA', null),
             ('Fly Khiva', 'KFH', 'D3'),
             ('Fly Oya', 'OYA', 'YI'),
             ('Fly Red Sea', 'RSG', 'Z4'),
             ('Fly Sky Airlines', 'FSU', null),
             ('Fly Yemen Airlines', 'FYO', null),
             ('Fly2Sky', 'VAW', 'F6'),
             ('Fly540', 'FFV', '5H'),
             ('Flyadeal', 'FAD', 'F3'),
             ('FlyBig', 'FLG', 'S9'),
             ('FlyDubai', 'FDB', 'FZ'),
             ('flyExclusive', 'JRE', null),
             ('Flying Business Aviation', 'FBX', null),
             ('Flyinggroup', 'FYL', null),
             ('Flylili', 'LIL', 'FL'),
             ('FlyMontserrat', 'MNT', '5M'),
             ('Flynas', 'KNE', 'XY'),
             ('FlyOne Armenia', 'FIE', '3F'),
             ('FlyPelican', 'FRE', 'FP'),
             ('FlySchool', 'FSM', null),
             ('Fort Aero', 'FRX', null),
             ('Fox Aviation', 'FIX', null),
             ('France - Air Force', 'FAF', null),
             ('France - Army', 'FMY', null),
             ('France - Navy', 'FNY', null),
             ('Franconia Air Service', 'FRC', null),
             ('Freebird Airlines Europe', 'FHM', 'MI'),
             ('Freedom Airline Express', 'SMK', '4K'),
             ('French Bee', 'FBU', 'BF'),
             ('FROST Air', 'FRO', null),
             ('Fuji Dream Airlines', 'FDA', 'JH'),
             ('FX TerraDynamics', 'FTX', null),
             ('Galistair Infinite Aviation', 'GTR', '8S'),
             ('Gama Aviation Cayman', 'GKY', null),
             ('Garuda Indonesia', 'GIA', 'GA'),
             ('Gelix Airlines', 'GAI', null),
             ('General Atomic AeroTech Systems', 'DOR', null),
             ('Genghis Khan Airlines', 'NMG', '9D'),
             ('Georgian Airways', 'TGZ', 'A9'),
             ('Geosky', 'GEL', 'D4'),
             ('Germanwings', 'GWI', '4U'),
             ('Germany - Air Force', 'GAF', null),
             ('Germany - DLR Flugbetriebe', 'LFO', null),
             ('Gesellschaft Fur Flugzieldarstellung', 'GFD', null),
             ('Gestair Aviation Malta', 'GSM', null),
             ('Getjet Airlines Latvia', 'DML', null),
             ('Ghana - Air Force', 'GHF', null),
             ('Global Air Transport', 'GAK', '5S'),
             ('Global Aviation', 'MSS', null),
             ('Global Jet Austria', 'GLJ', null),
             ('Global Reach Aviation', 'GAV', null),
             ('Global X', 'GXA', 'G6'),
             ('Go First', 'GOW', 'G8'),
             ('Go2Sky', 'RLX', '6G'),
             ('GOL Linhas Aereas', 'GLO', 'G3'),
             ('Gouvernement du Quebec', 'QUE', null),
             ('Grafair', 'GFM', null),
             ('Grand China Air', 'GDC', 'CN'),
             ('Greater Bay Airlines', 'HGB', 'HB'),
             ('Greece - Army', 'HLA', null),
             ('Green Africa Airways', 'GWG', 'Q9'),
             ('Gryphon Air', 'GRG', null),
             ('Gulf Air', 'GFA', 'GF'),
             ('Gulf Wings', 'GWC', null),
             ('Gum Air', 'GUM', null),
             ('GX Airlines', 'CBG', 'GX'),
             ('Hai Au Aviation', 'HAI', null),
             ('Hala Air', 'HTP', 'HG'),
             ('Hangar 8', 'HGR', null),
             ('Harmony Jets', 'HMJ', null),
             ('Haute Aviation', 'HUE', null),
             ('Hayways', 'HYY', 'Y5'),
             ('Heli Air Monaco', 'MCM', 'YO'),
             ('Heli Holland', 'HHE', null),
             ('Heli Service International', 'HSO', null),
             ('Helicol', 'HEL', null),
             ('Helijet International', 'JBA', null),
             ('Helistar', 'HSR', null),
             ('HELITY Copter Airlines', 'HTY', null),
             ('Helvetic Airways', 'OAW', '2L'),
             ('Hera Flight', 'HER', null),
             ('Heron Aviation', 'HRN', null),
             ('Hi Fly', 'HFY', '5K'),
             ('Himalaya Airlines', 'HIM', 'H9'),
             ('HiSky', 'HYM', 'H7'),
             ('HK express', 'HKE', 'UO'),
             ('Hokkaido Air System', 'NTH', null),
             ('Hong Kong - Government Flying Service', 'GFS', null),
             ('Hong Kong Airlines', 'CRK', 'HX'),
             ('Horizon Air', 'QXE', 'QX'),
             ('HTM Helicopter Travel Munich', 'HTM', null),
             ('Hungary - Air Force', 'HUF', null),
             ('Hydro Quebec', 'HYD', '0Q'),
             ('I-Fly', 'RSY', 'F7'),
             ('IAS Medical', 'MDI', null),
             ('IBC Airways', 'CSQ', 'II'),
             ('Iberia Express', 'IBS', 'I2'),
             ('Ibex Airlines', 'IBX', 'FW'),
             ('Icar Air', 'RAC', null),
             ('Icelandair', 'ICE', 'FI'),
             ('IFL Group', 'IFL', null),
             ('Image Air Charter', 'BMG', null),
             ('India - Air Force', 'IFC', null),
             ('IndiaOne Air', 'IOA', 'I7'),
             ('Indonesia AirAsia', 'AWQ', 'QZ'),
             ('Inner Mongolia Express', 'IME', null),
             ('Integra Jet', 'IJR', null),
             ('InterCaribbean Airways', 'IWY', 'JY'),
             ('International Jet Management', 'IJM', null),
             ('Iran Air', 'IRA', 'IR'),
             ('Iran Aseman Airlines', 'IRC', 'EP'),
             ('Iraqi Airways', 'IAW', 'IA'),
             ('Island Wings', 'IWL', null),
             ('ITA Airways', 'ITY', 'AZ'),
             ('Italy - Air Force', 'IAM', null),
             ('Italy - Coast Guard', 'GCI', null),
             ('iXAir', 'IXR', null),
             ('J D Aviation', 'JDA', null),
             ('Jackson Demolition Service', 'JDS', null),
             ('Japan Air Commuter', 'JAC', 'JC'),
             ('Japan Transocean Air', 'JTA', 'NU'),
             ('Jazeera Airways', 'JZR', 'J9'),
             ('JC Bamford Excavators', 'JCB', null),
             ('Jet Aviation Flight Services', 'JAS', null),
             ('Jet Concierge Club', 'JCO', null),
             ('Jet Executive', 'JEI', null),
             ('Jet It', 'JIT', null),
             ('Jet Logistics', 'JLG', null),
             ('Jet OUT', 'CRE', null),
             ('Jet Story', 'JDI', null),
             ('Jet View', 'JVW', null),
             ('Jetbee Czech', 'JBC', null),
             ('Jetcall', 'JCL', null),
             ('JetFlite', 'JEF', null),
             ('JetHouse', 'JTH', null),
             ('Jetlines', 'CJL', 'AU'),
             ('JetNEXA', 'JNX', null),
             ('JetRight', 'JRT', null),
             ('JetSMART', 'JAT', 'JA'),
             ('JetSMART Colombia', 'JEC', 'J6'),
             ('Jetspremier', 'JPM', null),
             ('Jetstar Asia', 'JSA', '3K'),
             ('JetStream', 'JSH', null),
             ('Jetsuite Air', 'RSP', null),
             ('Jetways Airlines', 'JWX', 'WU'),
             ('Jiangsu Jingdong Cargo Airlines', 'JDL', 'JG'),
             ('Jiangxi Express Commuter Aviation', 'KXA', null),
             ('Jinxiang Airlines', 'JXX', null),
             ('JoinJet', 'JNJ', null),
             ('Jonika', 'JNK', null),
             ('Jordan Aviation', 'JAV', 'R5'),
             ('JoyAir', 'JOY', 'JR'),
             ('Jsky Airlines', 'ISP', null),
             ('Jubba Airways', 'JBW', '3J'),
             ('Juneyao Air', 'DKH', 'HO'),
             ('K&R Aviation', 'OPN', null),
             ('K5-Aviation Germany', 'KAY', null),
             ('Kalitta Air', 'CKS', 'K4'),
             ('Kalitta Charters II', 'KII', 'K5'),
             ('Kamaka Air', 'KMK', null),
             ('Kargo Xpress', 'KXP', 'WW'),
             ('Keewatin Air', 'KEW', 'FK'),
             ('Kenai Aviation', 'KNW', null),
             ('Kenn Borek Air', 'KBA', '4K'),
             ('Kenya Airways', 'KQA', 'KQ'),
             ('Key Lime Air', 'LYM', 'KG'),
             ('Kingfisher Air', 'BEZ', null),
             ('KlasJet', 'KLJ', null),
             ('KLM Cityhopper', 'KLC', 'WA'),
             ('KN Helicopters', 'SHW', null),
             ('Korea Aerospace University', 'HGD', null),
             ('Kosmos Airlines', 'KSM', null),
             ('Kudlik Aviation', 'KUK', null),
             ('Kuwait Airways', 'KAC', 'KU'),
             ('L.J. Aviation', 'LJY', null),
             ('La Compagnie', 'DJT', 'B0'),
             ('Labcorp', 'SKQ', null),
             ('LADE', 'LDE', '5U'),
             ('Lao Airlines', 'LAO', 'QV'),
             ('LAS Cargo', 'LAU', '4L'),
             ('LATAM Airlines', 'LAN', 'LA'),
             ('LATAM Cargo', 'LCO', 'UC'),
             ('LATAM Cargo Colombia', 'LAE', 'L7'),
             ('LATAM Colombia', 'ARE', '4C'),
             ('LATAM Paraguay', 'LAP', 'PZ'),
             ('Latvia - Air Force', 'LAF', null),
             ('Leader', 'LSA', null),
             ('Legacy Airways', 'LGF', null),
             ('Legends Airways', 'DVY', null),
             ('Libya - Air Force', 'LBF', null),
             ('Libyan Express', 'LXX', null),
             ('Liebherr Aerospace', 'LHB', null),
             ('Lift', 'GBB', 'GE'),
             ('Lion Helicopters', 'LHE', null),
             ('Lithuania - Air Force', 'LYF', null),
             ('LLC H3Operations', 'UHO', null),
             ('Lone Star Aviators', 'BST', null),
             ('Longtail Aviation', 'LGT', '6T'),
             ('LOT', 'LOT', 'LO'),
             ('Lufthansa', 'DLH', 'LH'),
             ('Lufthansa City', 'LHX', 'VL'),
             ('Lufttransport', 'LTR', null),
             ('Lunds Universitet', 'UNY', null),
             ('Luxaviation', 'LXA', null),
             ('Luxaviation E.A', 'LMJ', null),
             ('Luxaviation UK', 'LNX', null),
             ('Luxwing', 'LWG', 'BN'),
             ('Lynden Air Cargo', 'LYC', 'L2'),
             ('Maersk', 'SRR', 'DJ'),
             ('Mahan Air', 'IRM', 'W5'),
             ('Malawi Airlines', 'MWI', '3W'),
             ('Malaysia Airlines', 'MAS', 'MH'),
             ('Maleth-Aero', 'MLT', 'DB'),
             ('Malta Air', 'MAY', 'MW'),
             ('Manasik Aviation', 'MNM', 'XN'),
             ('Mann Yadanarpon Airlines', 'MYP', '7Y'),
             ('Map Linhas Aereas', 'PAM', '7M'),
             ('Marathon Airlines', 'MTO', 'O8'),
             ('Martinaire', 'MRA', null),
             ('Massey University School of Aviation', 'MSY', null),
             ('Mater Logistics', 'TKH', null),
             ('Mavi Gok Airlines', 'MGH', '4M'),
             ('Max Air', 'FCE', null),
             ('Maxair', 'NTW', null),
             ('Maya Island Air', 'MYD', '2M'),
             ('McNeely Charter Services', 'MDS', null),
             ('Med-Trans', 'MEK', null),
             ('Medimpact', 'NDG', null),
             ('Mel Air', 'MDO', '5M'),
             ('Mercury Air Cargo', 'MEC', '4X'),
             ('Meridian Air Company', 'MMM', null),
             ('Mesa Airlines', 'ASH', 'YV'),
             ('Mexicana', 'MEX', null),
             ('Mexico - Government', 'MXG', null),
             ('MHS Aviation', 'MHV', 'M2'),
             ('MIAT Mongolian Airlines', 'MGL', 'OM'),
             ('Midamerica Jet', 'MJR', null),
             ('Middle Tennessee State University', 'MTU', null),
             ('Midwest Aviation Division', 'MWT', null),
             ('Mingalar', 'KBZ', 'K7'),
             ('MNG Airlines', 'MNB', 'MB'),
             ('Moçambique Expresso', 'MXE', null),
             ('Monacair', 'MCR', 'QM'),
             ('Morningstar Air Express', 'MAL', null),
             ('Mountain Air Cargo', 'MTN', null),
             ('Mountain Flyers', 'MFB', null),
             ('Multiflight', 'MFT', null),
             ('My Indo Airlines', 'MYU', '2Y'),
             ('My Jet Saver', 'MJS', null),
             ('Myanmar National Airlines', 'UBA', 'UB'),
             ('Naljets', 'APX', null),
             ('Namibia - Defence Force', 'NDF', null),
             ('National Air Charters', 'JYA', 'JY'),
             ('National Airways', 'NAE', '9Y'),
             ('National Jet Express', 'JTE', 'NC'),
             ('NATO', 'OAN', null),
             ('Naysa', 'NAY', 'ZN'),
             ('Neojets', 'NJZ', null),
             ('Nepal Airlines', 'RNA', 'RA'),
             ('Netherlands - Coast Guard', 'NCG', null),
             ('Netherlands - Royal Air Force', 'NAF', null),
             ('NetJets Europe', 'NJE', null),
             ('Network Aviation', 'NWK', null),
             ('New England Patriots', 'UDG', null),
             ('NHC Northern Helicopter', 'NHC', null),
             ('NHV Helicopters', 'NHZ', null),
             ('Niger Airlines', 'NIN', '6N'),
             ('Nile Air', 'NIA', 'NP'),
             ('Noble Air Charter', 'JLJ', null),
             ('Nolinor Aviation', 'NRL', 'N5'),
             ('Nomadic Aviation', 'OMD', null),
             ('Nordic Unmanned', 'NOU', null),
             ('NordStar', 'TYA', 'Y7'),
             ('Norlandair', 'FNA', null),
             ('Norse', 'NBT', 'N0'),
             ('Norsk Luftambulanse', 'DOC', null),
             ('North Central', 'NCJ', null),
             ('North Star Aviation', 'MVK', null),
             ('North-Wright Airways', 'NWL', 'HW'),
             ('Northern Air', 'NLI', null),
             ('Northern Jet Management', 'NJM', null),
             ('Northway Aviation', 'NAL', null),
             ('Northwestern Air', 'PLR', 'J3'),
             ('Norwegian', 'NOZ', 'DY'),
             ('Nouvelair Tunisie', 'LBT', 'BJ'),
             ('Novair', 'NAI', 'NG'),
             ('Novoair', 'NVQ', 'VQ'),
             ('Offshore Helicopter Services', 'ULR', null),
             ('OK Aviation', 'NTF', null),
             ('Oklahoma State University', 'OST', null),
             ('Olympus Airways', 'OLY', null),
             ('Oman Air', 'OMA', 'WY'),
             ('Omni Air Transport', 'DRL', null),
             ('Omni Taxi Aereo', 'OMI', null),
             ('One Airways', 'OEW', 'OX'),
             ('Oriental Air Bridge', 'ORC', 'OC'),
             ('Ornge Air', 'PUL', null),
             ('Oscar Jet', 'OSJ', null),
             ('OTT Airlines', 'OTT', 'JF'),
             ('Owenair', 'OWE', null),
             ('P80 Air', 'PMG', null),
             ('Pacific Coast Jet', 'PXT', null),
             ('PADAviation', 'PVD', null),
             ('PAL Aerospace', 'SPR', null),
             ('PAL Express', 'GAP', '2P'),
             ('Pan American Airways', 'PAA', 'PN'),
             ('Pan Europeenne Air Service', 'PEA', null),
             ('Panellenic Airlines', 'RJB', null),
             ('Panorama Aviation', 'PNO', null),
             ('Pascan Aviation', 'PSC', 'P6'),
             ('Patient Airlift Services', 'PLZ', null),
             ('Patriot Aviation', 'PTT', null),
             ('PDG Aviation Services', 'PDG', null),
             ('Pegasus', 'PGT', 'PC'),
             ('Pel-Air', 'PFY', null),
             ('People''s', 'PEV', 'PE'),
             ('Perimeter Aviation', 'PAG', 'YP'),
             ('Peru - Navy', 'INP', null),
             ('Petropavlovsk-Kamchatsky Air', 'PTK', null),
             ('Philippine Airlines', 'PAL', 'PR'),
             ('Phoenix Aerospace', 'PIX', null),
             ('Phoenix East Aviation', 'JED', null),
             ('Pilatus Flugzeugwerke', 'PCH', null),
             ('Pineapple Air', 'PNP', null),
             ('Pivot Airlines', 'GGN', 'ZX'),
             ('Placar Linhas Aereas', 'PLS', null),
             ('PlaneSense', 'CNS', null),
             ('Platoon Aviation', 'PTN', null),
             ('Plus Ultra', 'PUE', 'PU'),
             ('Pobeda', 'PBD', 'DP'),
             ('Poland - Navy', 'PNY', null),
             ('Polar Airlines', 'RKA', 'PI'),
             ('populAir', 'APF', 'HP'),
             ('Porter Airlines Canada', 'POE', 'PD'),
             ('Portugal - Army', 'POA', null),
             ('Portugalia Airlines', 'PGA', 'NI'),
             ('Pradhaan Air Express', 'PRX', '6P'),
             ('Precision Air', 'PRF', 'PW'),
             ('Premier Jets', 'PJI', null),
             ('Presidential Aviation', 'PRD', null),
             ('Prime Aviation.', 'PKZ', null),
             ('Priority Air Charter', 'PRY', null),
             ('Private Jet Center', 'PJC', null),
             ('Private Wings', 'PWF', 'JW'),
             ('ProAir Aviation', 'PAV', null),
             ('Propair', 'PRO', null),
             ('Purdue University', 'PDU', null),
             ('Qanot Sharq', 'QNT', 'HH'),
             ('QantasLink', 'QLK', null),
             ('Qatar Airways', 'QTR', 'QR'),
             ('Qayatawa Air', 'QYT', null),
             ('Qeshm Airlines', 'QSM', 'QB'),
             ('QinetiQ / Empire Test Pilots School', 'ETP', null),
             ('Quanta Aviation Services', 'PWR', null),
             ('Quick Air Jet Charter', 'QAJ', null),
             ('RAF-Avia', 'MTL', 'MT'),
             ('RAM Express', 'RXP', null),
             ('Ravenair', 'RVR', null),
             ('REACH Air Medical Services', 'REH', null),
             ('Really Cool Airlines', 'LUV', null),
             ('Rectrix Aviation', 'RIX', null),
             ('Red Sea Airlines', 'RSX', '4S'),
             ('Red Wings', 'RWZ', 'WZ'),
             ('Redstar Aviation', 'RHH', null),
             ('REGA Swiss Air-Ambulance', 'SAZ', null),
             ('Regency Air', 'RGY', null),
             ('Reliable Airlines', 'HPN', null),
             ('Renegade Air', 'RNG', null),
             ('Republic Airways', 'RPA', 'YX'),
             ('Rex', 'RXA', 'ZL'),
             ('Rhoades Aviation', 'RDS', 'T4'),
             ('Richmor Aviation', 'RJC', null),
             ('RiseAir', 'WEW', '4T'),
             ('Romania - Air Force', 'ROF', null),
             ('Roraima Airways', 'ROM', null),
             ('Rossiya', 'SDM', 'FV'),
             ('Royal Air Freight', 'RAX', null),
             ('Royal Brunei Airlines', 'RBA', 'BI'),
             ('Royal Wings', 'RYW', 'JO'),
             ('RS Avia', 'URA', null),
             ('Ruili Airlines', 'RLH', 'DR'),
             ('Rusline', 'RLU', '7R'),
             ('Russia - 224th Flight Unit State Airline', 'TTF', null),
             ('Russia - National Guard', 'RIF', null),
             ('Rutaca Airlines', 'RUC', '5R'),
             ('RwandAir', 'RWD', 'WB'),
             ('Ryan Air (USA)', 'RYA', '7S'),
             ('Ryanair UK', 'RUK', 'RK'),
             ('SA Red Cross Air Mercy Service', 'AMD', null),
             ('SAAB Nyge Aero', 'TGT', null),
             ('Safari Express Cargo', 'SXY', 'ZF'),
             ('Saha Airlines', 'IRZ', null),
             ('Saint Louis University', 'BKN', null),
             ('Salzburg Jet Aviation', 'MOZ', null),
             ('Samoa Airways', 'PAO', 'OL'),
             ('Sansa', 'LRS', 'RZ'),
             ('Sardinian Sky Service', 'SSR', null),
             ('SAS Connect', 'SZS', 'SL'),
             ('SATA Air Acores', 'SAT', 'SP'),
             ('Saudi Arabia - Air Force', 'RSF', null),
             ('Saudia', 'SVA', 'SV'),
             ('Sawyer Aviation', 'SJA', null),
             ('SC Aviation', 'COL', null),
             ('SCAT', 'VSV', 'DV'),
             ('Scoot', 'TGW', 'TR'),
             ('SEair International', 'SGD', 'XO'),
             ('Secure Air Charter', 'JCM', null),
             ('Sepehran Airlines', 'SHI', 'IS'),
             ('Serene Air', 'SEP', 'ER'),
             ('Servizi Aerei', 'SNM', null),
             ('Severstal Aircompany', 'SSF', 'D2'),
             ('Shell Aviation', 'PEX', null),
             ('Shirak Avia', 'SHS', '5G'),
             ('Shuttle America', 'TCF', 'S5'),
             ('Sichuan Airlines', 'CSC', '3U'),
             ('Sierra Charlie Aviation', 'SCA', null),
             ('Sierra West Airlines', 'PKW', null),
             ('Silk Way Airlines', 'AZQ', 'ZP'),
             ('Silkavia', 'USA', 'US'),
             ('Silver Air', 'SLD', null),
             ('Silver Cloud Air', 'SCR', null),
             ('Singapore - Air Force', 'SAF', null),
             ('Singapore Airlines Cargo', 'SQC', null),
             ('Sino Jet Beijing', 'JBE', null),
             ('Sirius Aero', 'CIG', 'SA'),
             ('SKS Airways', 'SJB', 'KI'),
             ('Sky Airline Peru', 'SKX', 'H8'),
             ('Sky Bus', 'HVY', null),
             ('SKY express', 'SEH', 'GQ'),
             ('Sky Helicopteros', 'HSY', null),
             ('Sky KG Airlines', 'KGK', null),
             ('Sky Mali', 'FML', 'ML'),
             ('Sky Quest', 'ERY', null),
             ('Sky Vision Airlines', 'SVI', 'SE'),
             ('Skyborne Airline Academy', 'SFY', null),
             ('SkyCare', 'PHX', null),
             ('Skyfirst', 'KFE', null),
             ('SkyJet Airlines', 'MSJ', 'M8'),
             ('SkyLink Express', 'SLQ', null),
             ('Skymark Executive', 'SMB', null),
             ('Skyservice Business Aviation', 'SYB', null),
             ('Skytaxi', 'IGA', 'TE'),
             ('Skytrans', 'SKP', 'QN'),
             ('SkyUp MT', 'SEU', 'U5'),
             ('Skyward Express', 'SEW', 'OW'),
             ('SkyWest Airlines', 'SKW', 'OO'),
             ('Slam Lavori Aerei', 'SLJ', null),
             ('Slovakia - Air Force', 'SQF', null),
             ('Slovenia - Air Force', 'LSV', null),
             ('Small Fly', 'GDM', null),
             ('Smart Jet', 'SAH', null),
             ('Smartavia', 'AUL', '5N'),
             ('SmartLynx', 'ART', '6Y'),
             ('SmartLynx Malta', 'LYX', '2N'),
             ('Smartwings Hungary', 'TVL', '7O'),
             ('Smartwings Slovakia', 'TVQ', '6D'),
             ('Solaseed Air', 'SNJ', '6J'),
             ('Solenta Aviation Cote D''Ivoire', 'SIV', null),
             ('Solinair', 'SOP', 'ZS'),
             ('Soma Jets', 'OZK', null),
             ('Sounds Air', 'SDA', null),
             ('South African Airways', 'SAA', 'SA'),
             ('Southern Airways Express', 'FDY', '9X'),
             ('Southwest Aircraft Charter', 'CAK', null),
             ('Southwind Airlines', 'STW', '2S'),
             ('Spain - Army', 'ETF', null),
             ('Spain - Guardia Civil', 'DGC', null),
             ('Sparfell Luftfahrt', 'LDX', null),
             ('Specialist Aviation Services', 'PLC', null),
             ('Spirit Airlines', 'NKS', 'NK'),
             ('Spree Flug', 'SFG', null),
             ('Spring Japan', 'SJO', 'IJ'),
             ('SprintAir Cargo', 'SAR', null),
             ('SriLankan Airlines', 'ALK', 'UL'),
             ('St Barth Commuter', 'SBU', 'PV'),
             ('STAjets', 'KFB', null),
             ('Star Air Cargo', 'BRH', null),
             ('Star Fly Wings', 'SYW', null),
             ('Star Wings', 'STQ', null),
             ('Starflyer', 'SFJ', '7G'),
             ('Starlink Aviation', 'TLK', 'Q4'),
             ('Starlux', 'SJX', 'JX'),
             ('Sterling Aviation', 'NSH', null),
             ('Su Airlines', 'SUE', null),
             ('Sudan Airways', 'SUD', 'SD'),
             ('Summit Aviation', 'YEL', null),
             ('Sun Air', 'SNR', 'SO'),
             ('Sun-Air', 'SUS', 'EZ'),
             ('Suncor Energy', 'JSN', null),
             ('Sundt Air', 'AKK', null),
             ('SunExpress', 'SXS', 'XQ'),
             ('Sunlight Air', 'RLB', '2R'),
             ('Sunstate Airlines', 'SSQ', null),
             ('Sunwing Airlines', 'SWG', 'WG'),
             ('Super Air Jet', 'SJV', 'IU'),
             ('Surf Air', 'URF', null),
             ('Surveillance Australia', 'BDF', null),
             ('Suzhou Aviation', 'CBW', null),
             ('Svenskt Ambulansflyg', 'SWE', null),
             ('SVG Air', 'SVD', null),
             ('Sweden - Coast Guard', 'KBV', null),
             ('Sweden - Swedish Maritime Administration', 'HMF', null),
             ('Swiftair', 'SWT', 'WT'),
             ('Swiss', 'SWR', 'LX'),
             ('Swiss Helicopter', 'HSI', null),
             ('Switzerland - Air Force', 'SUI', null),
             ('Sylt Air', 'AWU', '7E'),
             ('Syphax Airlines', 'SYA', 'Y3'),
             ('T''way Air', 'TWB', 'TW'),
             ('TAB Cargo', 'BOL', '2L'),
             ('TAG Aviation', 'VIP', null),
             ('TAG Aviation Cayman', 'TCJ', null),
             ('TAG Aviation San Marino', 'TAG', null),
             ('Taiga Air', 'TGA', null),
             ('Tajik Air', 'TJK', '7J'),
             ('Tanana Air Service', 'TNR', 'Z3'),
             ('Taquan Air', 'TQN', 'K3'),
             ('Tarco Aviation', 'TQQ', '3T'),
             ('Tashkent Air', 'TSK', null),
             ('Tassili Airlines', 'DTH', 'SF'),
             ('Tbilisi Airways', 'TBC', 'TD'),
             ('Team Global Express', 'TFX', null),
             ('Terra Avia', 'TVR', 'T8'),
             ('Texel Air Australasia', 'TNZ', null),
             ('Thai AirAsia', 'AIQ', 'FD'),
             ('Thai Airways', 'THA', 'TG'),
             ('Thai VietJet Air', 'TVJ', 'VZ'),
             ('Thales UK Flight Inspection Service', 'CLB', null),
             ('The Mitre Corporation', 'MIP', null),
             ('Thrust Flight', 'TRF', null),
             ('Tianjin Air Cargo', 'CTJ', 'HT'),
             ('Tibet Airlines', 'TBA', 'TV'),
             ('Time Air', 'TIE', null),
             ('Titan Airways', 'AWC', 'ZT'),
             ('Total Express', 'TOT', null),
             ('Toyo Aviation', 'TOY', null),
             ('Tradewind Aviation', 'GPD', 'TJ'),
             ('Trans Am Aero Express del Ecuador', 'RTM', '7T'),
             ('Trans Island Airways', 'GGT', null),
             ('Transair', 'GTS', 'R2'),
             ('Transavia', 'TRA', 'HV'),
             ('Transaviabaltika', 'KTB', null),
             ('TransNusa', 'TNU', '8B'),
             ('Travira Air', 'TVV', null),
             ('Tri-State Aero', 'TSS', null),
             ('Trigana Air', 'TGN', 'IL'),
             ('Tropic Ocean Airways', 'FTO', 'TI'),
             ('TUI Airlines Belgium', 'JAF', 'TB'),
             ('TUI Airways', 'TOM', 'BY'),
             ('TUI fly Nordic', 'BLX', '6B'),
             ('TUM AeroCarga', 'MCS', 'T2'),
             ('Tunisair Express', 'TUX', 'UG'),
             ('Turkey - Air Force', 'HVK', null),
             ('Turkish Airlines', 'THY', 'TK'),
             ('Turkmenistan Airlines', 'TUA', 'T5'),
             ('Tus Air', 'CYF', 'U8'),
             ('Tyrol Air Ambulance', 'TYW', null),
             ('Tyrolean Jets & Services Malta', 'TYJ', null),
             ('Uganda Airlines', 'UGD', 'UR'),
             ('Ukraine Air Alliance', 'UKL', null),
             ('Ukrainian Wings', 'UWJ', null),
             ('Ultimate Jet', 'UJC', 'UE'),
             ('UND Aerospace', 'NDU', null),
             ('Uni-Fly', 'UNC', null),
             ('Uni-Top Airlines', 'UTP', 'UW'),
             ('Union Aviation', 'UAG', null),
             ('United Airlines', 'UAL', 'UA'),
             ('United Aviate Academy', 'VAR', null),
             ('United Kingdom - Air Ambulance', 'HLE', null),
             ('United Kingdom - UK Royal/VIP Flights', 'KRF', null),
             ('United Nigeria Airlines', 'NUA', 'UN'),
             ('United States - FAA', 'NHK', null),
             ('United States - NOA', 'NOA', null),
             ('United States - US Marshals Service', 'MSH', null),
             ('University of Central Missouri', 'UCM', null),
             ('Uniworld Air Cargo', 'UCG', 'U7'),
             ('UR Airlines', 'UBD', 'UD'),
             ('Urumqi Air', 'CUH', 'UQ'),
             ('USA Jet Airlines', 'JUS', 'UJ'),
             ('Utair', 'UTA', 'UT'),
             ('Uzbekistan Airways', 'UZB', 'HY'),
             ('Valletta Airlines', 'HOT', null),
             ('ValueJet', 'FVJ', 'VK'),
             ('Varesh Airlines', 'VRH', null),
             ('Venezolana', 'VNE', 'WW'),
             ('Venture Aviation Group', 'VET', null),
             ('VeriJet', 'WSP', null),
             ('Victory Air', 'FTN', null),
             ('VietJet Air', 'VJC', 'VJ'),
             ('Vietravel Airlines', 'VAG', 'VU'),
             ('Virgin Atlantic International', 'VGI', null),
             ('Virgin Australia Regional', 'OZW', null),
             ('VistaJet', 'VJT', null),
             ('Vistara', 'VTI', 'UK'),
             ('VoePass', 'PTB', '2Z'),
             ('Volaris', 'VOI', 'Y4'),
             ('Volaris El Salvador', 'VOS', 'N3'),
             ('Volga-Dnepr Airlines', 'VDA', 'VI'),
             ('Voluxis', 'VXS', null),
             ('Voyageur Airways', 'VAL', 'VC'),
             ('VW Air Service', 'BTX', null),
             ('Warbelows Air Ventures', 'WAV', '4W'),
             ('Wermlandsflyg', 'SWX', null),
             ('West Air', 'CHB', 'PN'),
             ('West Air Sweden', 'SWN', 'T2'),
             ('West Coast Charters', 'WCC', null),
             ('Westair Aviation', 'WAA', null),
             ('Western Air', 'WST', 'WU'),
             ('Western Aircraft', 'STT', 'ST'),
             ('WestJet Encore', 'WEN', 'WR'),
             ('White', 'WHT', 'WI'),
             ('Wiggins Airways', 'WIG', null),
             ('Winair', 'WIA', 'WM'),
             ('Windrose Airlines', 'WRC', '7W'),
             ('Wingo', 'RPB', 'P5'),
             ('Wings Air', 'WON', 'IW'),
             ('Wizz Air Abu Dhabi', 'WAZ', '5W'),
             ('Wizz Air UK', 'WUK', 'W9'),
             ('World Atlantic Airlines', 'WAL', 'WL'),
             ('World2Fly', 'WFL', '2W'),
             ('Worldwide Jet Charter', 'WWI', null),
             ('XE Jet', 'XEJ', null),
             ('Xfly', 'EST', 'EE'),
             ('Xinjiang Skylink General Aviation', 'KGA', null),
             ('Yakutia Airlines', 'SYL', 'R3'),
             ('YanAir', 'ANR', 'YE'),
             ('Yemenia', 'IYE', 'IY'),
             ('YTO Cargo Airlines', 'HYT', 'YG'),
             ('Z Air', 'EZR', '7Z'),
             ('Zagros Airlines', 'IZG', 'ZO'),
             ('Zanair', 'TAN', null),
             ('Zenith Aviation', 'BZE', null),
             ('Zeusch Aviation', 'SUZ', null),
             ('Zil Air', 'SYZ', null),
             ('Zimex Aviation Austria', 'AZD', 'ZX'),
             ('Zooom', 'ZOM', 'ZO'),
             ('ZYB Lily Jet', 'MZT', null)) AS v(name, icao, iata)
WHERE NOT EXISTS (SELECT 1
                  FROM airline a
                  WHERE a.name = v.name);
