documentation:
  - changed-files:
      - any-glob-to-any-file:
          - docs/docs/**
          - docs/src/**
          - docs/static/**

web:
  - changed-files:
      - any-glob-to-any-file:
          - src/**
          - static/**
