documentation:
  - changed-files:
      - any-glob-to-any-file:
          - docs/docs/**
          - docs/src/**
          - docs/static/**
web:
  - all:
      - changed-files:
          - any-glob-to-any-file:
              - src/**
              - static/**
          - all-globs-to-all-files:
              - '!static/airlines/**'
data:
  - changed-files:
      - any-glob-to-any-file:
          - data/**
'changelog:skip':
  - changed-files:
      - any-glob-to-all-files:
          - data/**
