CREATE TABLE "public"."airline"
(
    "id"   SERIAL NOT NULL,
    "name" TEXT   NOT NULL,
    "icao" TEXT,
    "iata" TEXT,

    CONSTRAINT "airline_pkey" PRIMARY KEY ("id")
);

INSERT INTO "public"."airline" (icao, iata, name)
VALUES ('EMC', NULL, '247 Aviation'),
       ('DAK', NULL, '4 Airways'),
       ('IHO', 'FE', '748 Air Services'),
       ('NKP', 'S5', 'Abakan Air'),
       ('BAR', NULL, 'Abu Dhabi Aviation'),
       ('SON', NULL, 'Acass Ireland'),
       ('AEE', 'A3', 'Aegean Airlines'),
       ('EUK', 'EG', 'Aer Lingus UK'),
       ('BLK', '5E', 'Aero'),
       ('AKF', NULL, 'Aero Asahi'),
       ('CTA', NULL, 'Aero Charter and Transport'),
       ('UKA', 'FO', 'Aero FlightOps UK'),
       ('EOK', 'RF', 'Aero K'),
       ('ANK', 'KA', 'Aero Nomad'),
       ('TKK', NULL, 'Aero Ways'),
       ('ADN', NULL, 'Aero-Dienst'),
       ('AFL', 'SU', 'Aeroflot'),
       ('AEZ', 'XZ', 'Aeroitalia'),
       ('ARG', 'AR', 'Aerolineas Argentinas'),
       ('NSO', 'P4', 'Aerolineas Sosa'),
       ('BOX', '3S', 'AeroLogic'),
       ('AMX', 'AM', 'Aeromexico'),
       ('OLO', 'DC', 'Aeronaves Dominicanas'),
       ('DFC', NULL, 'Aeropartner'),
       ('RER', '6G', 'Aeroregional'),
       ('TAA', NULL, 'Aeroservicios de la Costa'),
       ('KRE', 'A4', 'Aerosucre'),
       ('AEP', NULL, 'Aerotec'),
       ('ATG', 'F5', 'Aerotranscargo'),
       ('DAP', 'V5', 'Aerovias DAP'),
       ('MCK', NULL, 'Aeroways'),
       ('AFF', NULL, 'AF-Aviation'),
       ('FSK', NULL, 'Africa Charter Airline'),
       ('AXK', 'XU', 'African Express Airways'),
       ('AAW', '8U', 'Afriqiyah Airways'),
       ('RUF', NULL, 'Air 1st Aviation'),
       ('ABN', 'ZB', 'Air Albania'),
       ('AYY', NULL, 'Air Alliance'),
       ('TAH', '6K', 'Air Anka'),
       ('ABY', 'G9', 'Air Arabia'),
       ('RBG', 'E5', 'Air Arabia Egypt'),
       ('KZR', 'KC', 'Air Astana'),
       ('AAE', 'CT', 'Air Atlanta Europe'),
       ('REU', 'UU', 'Air Austral'),
       ('ABB', 'KF', 'Air Belgium'),
       ('LBR', NULL, 'Air Borealis'),
       ('VBW', '2J', 'Air Burkina'),
       ('MSC', 'SM', 'Air Cairo'),
       ('ACA', 'AC', 'Air Canada'),
       ('FWI', 'TX', 'Air Caraibes'),
       ('CMF', NULL, 'Air Care Alliance'),
       ('LHA', 'GI', 'Air Central'),
       ('CGN', '9H', 'Air Changan'),
       ('EDC', NULL, 'Air Charter Scotland'),
       ('AGR', NULL, 'Air Charters Europe'),
       ('CCA', 'CA', 'Air China'),
       ('CNM', NULL, 'Air China Inner Mongolia'),
       ('CPV', NULL, 'Air Corporate'),
       ('VRE', 'HF', 'Air Cote d''Ivoire'),
       ('DKN', NULL, 'Air Deccan'),
       ('DJB', 'DJ', 'Air Djibouti'),
       ('DLA', 'EN', 'Air Dolomiti'),
       ('AEA', 'UX', 'Air Europa'),
       ('XLL', NULL, 'Air Excel'),
       ('WAF', 'F4', 'Air Flamenco'),
       ('HOP', 'A5', 'Air France Hop'),
       ('GRL', 'GL', 'Air Greenland'),
       ('HFA', NULL, 'Air Haifa'),
       ('HAT', 'HT', 'Air Horizont'),
       ('AIC', 'AI', 'Air India'),
       ('AIE', '3H', 'Air Inuit'),
       ('KWX', NULL, 'Air Key West'),
       ('KOR', 'JS', 'Air Koryo'),
       ('LSJ', 'DU', 'Air Liaison'),
       ('RLY', NULL, 'Air Loyaute'),
       ('AMH', NULL, 'Air Macran'),
       ('MBB', 'ZM', 'Air Manas'),
       ('MAR', 'MV', 'Air Mediterranean'),
       ('NTR', 'NM', 'Air Moana'),
       ('AMT', NULL, 'Air Mountain'),
       ('ANG', 'PX', 'Air Niugini'),
       ('ANE', 'YW', 'Air Nostrum'),
       ('AOM', NULL, 'Air Ocean Maroc'),
       ('APK', 'P4', 'Air Peace'),
       ('RAR', 'GZ', 'Air Rarotonga'),
       ('SPM', 'PJ', 'Air Saint-Pierre'),
       ('SZN', 'HC', 'Air Senegal'),
       ('SEY', 'HM', 'Air Seychelles'),
       ('ASB', NULL, 'Air Spray'),
       ('VTA', 'VT', 'Air Tahiti'),
       ('ATC', 'TC', 'Air Tanzania'),
       ('TOA', NULL, 'Air Tetiaroa'),
       ('TIN', '8T', 'Air Tindi'),
       ('EAT', NULL, 'Air Transport Europe'),
       ('OTC', 'A6', 'Air Travel'),
       ('AVN', 'NF', 'Air Vanuatu'),
       ('AWI', 'ZW', 'Air Wisconsin'),
       ('AZW', 'UM', 'Air Zimbabwe'),
       ('TWG', NULL, 'Air-Taxi Europe'),
       ('FGB', NULL, 'Air65 Aviation'),
       ('AXM', 'AK', 'AirAsia'),
       ('XAX', 'D7', 'AirAsia X'),
       ('ABW', 'RU', 'AirBridgeCargo Airlines'),
       ('BCO', NULL, 'Airbus Beluga Transport'),
       ('ACI', 'SB', 'Aircalin'),
       ('RVJ', NULL, 'Aircraft Management Group'),
       ('AEG', NULL, 'Airest'),
       ('AFE', 'FS', 'Airfast Indonesia'),
       ('GJM', 'RE', 'Airhub Airlines'),
       ('XAK', 'P2', 'Airkenya Express'),
       ('ALI', NULL, 'Airlift'),
       ('JAR', NULL, 'Airlink'),
       ('RMX', 'MR', 'AirMaster'),
       ('USC', NULL, 'AirNet'),
       ('APC', NULL, 'Airpac Airlines'),
       ('ASL', 'JU', 'AirSERBIA'),
       ('XSR', NULL, 'AirShare'),
       ('XSM', NULL, 'AirSmart'),
       ('AQS', NULL, 'Airstream'),
       ('TOW', '9L', 'AirTanker'),
       ('ATY', NULL, 'AirTraffic'),
       ('WZE', NULL, 'Airwaze'),
       ('PNX', NULL, 'AIS Airlines'),
       ('IAD', 'I5', 'AIX Connect'),
       ('AKJ', 'QP', 'Akasa Air'),
       ('TTR', NULL, 'Alaman Air'),
       ('ASA', 'AS', 'Alaska Airlines'),
       ('LAV', NULL, 'AlbaStar'),
       ('LUC', NULL, 'Albinati Aeronautics'),
       ('KHH', 'DQ', 'Alexandria Airlines'),
       ('AAJ', '5E', 'Alfa Airlines'),
       ('LID', 'D4', 'Alidaunia'),
       ('TJD', NULL, 'Aliserio'),
       ('ALN', NULL, 'Alkan Air'),
       ('ANA', 'NH', 'All Nippon Airways'),
       ('LLR', '9I', 'Alliance Air'),
       ('ALE', NULL, 'Alliance Executive Jets'),
       ('LMU', 'UJ', 'AlMasria Universal Airlines'),
       ('APP', 'AL', 'AlpAvia'),
       ('BIC', NULL, 'Alphaland Aviation'),
       ('ALX', NULL, 'Alpi Jets'),
       ('FSE', NULL, 'Alpine Flightservice'),
       ('AGH', NULL, 'Altagna'),
       ('STY', NULL, 'Altius Aviation'),
       ('AMV', NULL, 'AMC Airlines'),
       ('AIA', '8R', 'Amelia'),
       ('GTW', NULL, 'American Air Charter'),
       ('AJB', NULL, 'American Jet'),
       ('AMF', 'A8', 'Ameriflight'),
       ('AJI', '7Z', 'Ameristar'),
       ('GEO', NULL, 'AMS Airlines'),
       ('AJP', NULL, 'Anap Jets'),
       ('ANS', 'O4', 'Andes Lineas Aereas'),
       ('AXL', 'Q3', 'Anguilla Air Services'),
       ('ADB', NULL, 'Antonov Airlines'),
       ('DWI', 'DM', 'Arajet'),
       ('AXR', NULL, 'Archer Air'),
       ('FAG', NULL, 'Argentina - Air Force'),
       ('RIE', 'EL', 'Ariella'),
       ('OAO', NULL, 'Arkhangelsk Airlines'),
       ('AMW', '6A', 'Armenia Airways'),
       ('ARU', 'AG', 'Aruba Airlines'),
       ('SYG', NULL, 'Ascend Airways'),
       ('TMG', 'GM', 'Asia Cargo Airlines'),
       ('LIC', NULL, 'Asia Sky Lines'),
       ('TXP', 'RS', 'Asian Express Airlines'),
       ('AAR', 'OZ', 'Asiana Airlines'),
       ('ABR', NULL, 'ASL Airlines'),
       ('TAY', '3V', 'ASL Airlines Belgium'),
       ('ABV', NULL, 'ASL Airlines UK'),
       ('ASJ', NULL, 'Astonjet'),
       ('ACP', '8V', 'Astral Aviation'),
       ('CYO', NULL, 'ATI Jet'),
       ('AFZ', NULL, 'Atlantic Flight Training Academy'),
       ('GTI', '5Y', 'Atlas Air'),
       ('CXK', NULL, 'ATP Flight School'),
       ('VAS', 'V8', 'Atran'),
       ('WPR', NULL, 'Auckland Rescue Helicopter'),
       ('AUR', 'GR', 'Aurigny Air Services'),
       ('CUS', NULL, 'Australia - Customs'),
       ('FPL', NULL, 'Australia - Federal Police'),
       ('ASF', NULL, 'Austria - Air Force'),
       ('AJO', NULL, 'Av8Jet'),
       ('ARR', NULL, 'Avalair Aircraft Management'),
       ('TTE', NULL, 'Avcenter'),
       ('VCJ', NULL, 'Avcon Jet Malta'),
       ('VXP', 'XP', 'Avelo Airlines'),
       ('AZS', 'ZR', 'Aviacon Zitotrans'),
       ('TPA', 'QT', 'Avianca Cargo'),
       ('GLG', '2K', 'Avianca Ecuador'),
       ('AVR', 'EX', 'Avianca Express'),
       ('VIT', NULL, 'Aviastar'),
       ('LKF', NULL, 'Aviation Advisor'),
       ('WCP', NULL, 'Aviator College'),
       ('INR', NULL, 'Avincis'),
       ('BNO', NULL, 'Avincis Aviation Norway'),
       ('NVD', 'X9', 'Avion Express'),
       ('MLH', '4X', 'Avion Express Malta'),
       ('ROI', '9V', 'Avior Airlines'),
       ('WEY', NULL, 'AWA'),
       ('BQA', NULL, 'AXIS Aviation'),
       ('AHY', 'J2', 'Azerbaijan Airlines'),
       ('AZO', 'A4', 'Azimuth'),
       ('RZO', 'S4', 'Azores Airlines'),
       ('AZU', 'AD', 'Azul'),
       ('AZV', 'ZF', 'Azur Air'),
       ('CFE', 'CJ', 'BA CityFlyer'),
       ('RHD', NULL, 'Babcock'),
       ('SQH', NULL, 'Backcountry Aviation'),
       ('BDR', 'J4', 'Badr Airlines'),
       ('VSB', NULL, 'BAe Systems Marine'),
       ('BRJ', NULL, 'Bairline'),
       ('BAV', 'QH', 'Bamboo Airways'),
       ('BKA', NULL, 'BankAir'),
       ('BVN', NULL, 'Baron Aviation Services'),
       ('BTK', 'ID', 'Batik Air'),
       ('BBT', 'B5', 'BBN Airlines'),
       ('BLS', 'JV', 'Bearskin Airlines'),
       ('BJN', NULL, 'Beijing Airlines'),
       ('BRU', 'B2', 'Belavia'),
       ('BCG', NULL, 'Belgium - Coast Guard'),
       ('NYB', NULL, 'Belgium - Navy'),
       ('BMJ', 'CH', 'Bemidji Airlines'),
       ('BRG', '8E', 'Bering Air'),
       ('BMA', '2T', 'BermudAir'),
       ('BYA', NULL, 'Berry Aviation'),
       ('BGH', '8H', 'BH Air'),
       ('BGB', NULL, 'Big Bend Community College'),
       ('BBC', 'BG', 'Biman Bangladesh Airlines'),
       ('BGL', NULL, 'Binani Air'),
       ('BIO', NULL, 'Bioflight'),
       ('TJJ', NULL, 'Blessings Aviation'),
       ('BDA', 'BZ', 'Blue Dart Aviation'),
       ('BJQ', NULL, 'Blue Jet Airways'),
       ('BBG', 'BZ', 'Bluebird Airways'),
       ('BSF', NULL, 'Bluesky Airways'),
       ('BOE', NULL, 'Boeing'),
       ('BBA', NULL, 'Bombardier'),
       ('BTQ', '4B', 'Boutique Air'),
       ('BIX', 'TT', 'Braathens International Airways'),
       ('BAY', NULL, 'Bravo Airways'),
       ('EXB', NULL, 'Brazil - Army'),
       ('MXY', 'MX', 'Breeze Airways'),
       ('BRD', '5B', 'Bridges Air Cargo'),
       ('BHL', NULL, 'Bristow Helicopters'),
       ('NOR', NULL, 'Bristow Norway'),
       ('BAW', 'BA', 'British Airways'),
       ('BRT', NULL, 'British International Helicopters'),
       ('BEL', 'SN', 'Brussels Airlines'),
       ('BHA', 'U4', 'Buddha Air'),
       ('BFL', 'J0', 'Buffalo Airways'),
       ('AFB', NULL, 'Bulgaria - Air Force'),
       ('LZB', 'FB', 'Bulgaria Air'),
       ('BFA', NULL, 'Burkina Faso - Government'),
       ('JMP', NULL, 'Business Wings'),
       ('BYS', NULL, 'BySky'),
       ('DBP', 'BU', 'CAA'),
       ('CSR', NULL, 'CAE'),
       ('CXE', '9Q', 'Caicos Express Airways'),
       ('CMD', NULL, 'Calstar'),
       ('KME', 'KR', 'Cambodia Airways'),
       ('CMM', NULL, 'CAMEX Adria Airlines'),
       ('CTG', NULL, 'Canada - Coast Guard'),
       ('TGO', NULL, 'Canada - Department of Transport'),
       ('ONT', NULL, 'Canada - Ontario Ministry of Natural Resources'),
       ('CFC', NULL, 'Canada - Royal Canadian Air Force'),
       ('SST', NULL, 'Canada - Royal Canadian Mounted Police'),
       ('SLG', NULL, 'Canada - Saskatchewan Air Ambulance Service'),
       ('AKT', '5T', 'Canadian North'),
       ('CNF', 'PM', 'CanaryFly'),
       ('MFC', NULL, 'Canlink Aviation'),
       ('KAP', '9K', 'Cape Air'),
       ('CBJ', 'JD', 'Capital Airlines'),
       ('CAD', '7D', 'Cardig Air'),
       ('CGF', NULL, 'Cargo Air'),
       ('CJT', 'W8', 'Cargojet Airways'),
       ('ICV', 'C8', 'Cargolux Italia'),
       ('CCK', NULL, 'Carlisle Air Group'),
       ('CRN', NULL, 'Carson Air'),
       ('CSJ', NULL, 'Castle Aviation'),
       ('CPA', 'CX', 'Cathay Pacific'),
       ('CVK', NULL, 'Cavok Air'),
       ('CBC', NULL, 'CB SkyShare'),
       ('CEB', '5J', 'Cebu Pacific'),
       ('KEM', '5Z', 'CemAir'),
       ('CTL', NULL, 'Central Air Southwest'),
       ('GLR', '9M', 'Central Mountain Air'),
       ('CAQ', NULL, 'Cerium Air'),
       ('GSW', 'GM', 'Chair Airlines'),
       ('CHZ', 'X6', 'Challenge Air Cargo'),
       ('ICL', '5C', 'Challenge Airlines IL'),
       ('RKJ', NULL, 'Charter Airlines'),
       ('HRT', NULL, 'Chartright Air'),
       ('HNL', NULL, 'CHC Helicopters Netherlands'),
       ('HKS', NULL, 'CHC Helikopter Service'),
       ('UEA', 'EU', 'Chengdu Airlines'),
       ('WDY', NULL, 'Chicago Jet Group'),
       ('CFI', NULL, 'China - Civil Aviation Administration'),
       ('CKK', 'CK', 'China Cargo Airlines'),
       ('HXA', 'G5', 'China Express Airlines'),
       ('CSN', 'CZ', 'China Southern Airlines'),
       ('CUA', 'KN', 'China United Airlines'),
       ('CQN', 'OQ', 'Chongqing Airlines'),
       ('MBK', 'MB', 'Chrono Jet'),
       ('CYC', NULL, 'Circadian Aviation'),
       ('CTV', 'QG', 'Citilink'),
       ('CAP', NULL, 'Civil Air Patrol'),
       ('EFY', 'VE', 'Clic'),
       ('OMT', 'H5', 'CM Airlines'),
       ('CSV', 'CQ', 'Coastal Aviation'),
       ('NJS', NULL, 'Cobham Aviation Services Australia'),
       ('CGZ', 'GY', 'Colorful Guizhou Airlines'),
       ('CXB', 'CS', 'Comlux Aruba'),
       ('MLM', NULL, 'Comlux Malta'),
       ('CPI', NULL, 'Compagnia Aeronautica Italiana'),
       ('FGD', NULL, 'Conair'),
       ('CGA', '8Z', 'Congo Airways'),
       ('UZA', NULL, 'Constanta Airline'),
       ('VCV', 'V0', 'Conviasa'),
       ('CAT', NULL, 'Copenhagen Airtaxi'),
       ('CXI', 'XR', 'Corendon Airlines Europe'),
       ('CPT', NULL, 'Corporate Air'),
       ('PHJ', NULL, 'Corporate Jet'),
       ('MSP', NULL, 'Costa Rica - Ministry of Public Security'),
       ('CUL', NULL, 'Coulson Aviation'),
       ('HRZ', NULL, 'Croatia - Air Force'),
       ('CRA', 'C8', 'Cronos Airlines'),
       ('CWN', 'FQ', 'Crown Airlines'),
       ('IRO', NULL, 'CSA Air'),
       ('TOG', NULL, 'CSM Aviation'),
       ('RGN', NULL, 'Cygnus Air'),
       ('CSA', 'OK', 'Czech Airlines'),
       ('CIE', NULL, 'Czechia - Government'),
       ('CCD', NULL, 'Dalian Airlines'),
       ('DAN', '9J', 'Dana Air'),
       ('DSO', NULL, 'Dassault Falcon Service'),
       ('DNU', 'R6', 'DAT LT'),
       ('DCW', NULL, 'DC Aviation'),
       ('DCU', NULL, 'DC Aviation San Marino'),
       ('DER', NULL, 'Deer Jet'),
       ('DAL', 'DL', 'Delta Air Lines'),
       ('DAR', NULL, 'Denmark - Army'),
       ('DAF', NULL, 'Denmark -Air Force'),
       ('DWA', NULL, 'Desert Wings Aviation'),
       ('DLN', NULL, 'Deucalion Aviation'),
       ('DAE', 'D5', 'DHL Aero Expreso'),
       ('DHA', 'Q7', 'DHL Air Austria'),
       ('DMS', NULL, 'Diamond Sky'),
       ('OCN', '4Y', 'Discover Airlines'),
       ('DKA', NULL, 'Dokia Air'),
       ('DAV', 'DO', 'Dornier Aviation Nigeria Aiep'),
       ('CBM', NULL, 'DragonFly Executive'),
       ('DLX', NULL, 'Dreamline Aviation'),
       ('DXE', 'OY', 'Dronamics Europe Airlines'),
       ('DUB', NULL, 'Dubai Air Wing'),
       ('CAH', NULL, 'E+S Air'),
       ('ERF', 'RF', 'E-Cargo Airlines'),
       ('EGE', NULL, 'Eagle Air'),
       ('FEI', NULL, 'Eagle Air Iceland'),
       ('EMD', NULL, 'EagleMed'),
       ('EWZ', NULL, 'East Wing'),
       ('ESR', 'ZE', 'Eastar Jet'),
       ('EAL', '2D', 'Eastern Airlines'),
       ('EAQ', NULL, 'Eastern Australia Airlines'),
       ('EZY', 'U2', 'easyJet'),
       ('EZS', 'DS', 'easyJet Switzerland'),
       ('ECC', NULL, 'Eclair Aviation'),
       ('ECO', '8J', 'EcoJet'),
       ('EDW', 'WK', 'Edelweiss Air'),
       ('EGY', NULL, 'Egypt - Air Force'),
       ('MSX', NULL, 'Egyptair Cargo'),
       ('ELY', 'LY', 'El Al'),
       ('EAF', '3E', 'Electra Airways'),
       ('EFG', NULL, 'Elifriulia'),
       ('EOS', NULL, 'Eliossola'),
       ('ELA', NULL, 'Elitaliana'),
       ('EAU', 'MA', 'Elitavia Malta'),
       ('MNU', '7Q', 'Elite Airways'),
       ('FIB', NULL, 'Elthuraya Aviation'),
       ('ERU', NULL, 'Embry-Riddle Aeronautical University'),
       ('EAG', NULL, 'Emerald Airlines UK'),
       ('UAE', 'EK', 'Emirates'),
       ('EMM', NULL, 'Emperor Aviation'),
       ('MJE', NULL, 'Empire Aviation'),
       ('EPT', NULL, 'Empresa Publica de Transporte Aereo Militar'),
       ('RLJ', NULL, 'Empyreal Jet'),
       ('DKT', NULL, 'Encore Air Cargo'),
       ('ENG', NULL, 'ENG Aviation'),
       ('ENY', 'MQ', 'Envoy'),
       ('GRV', NULL, 'Epsilon Aviation'),
       ('ESF', 'E7', 'Estafeta'),
       ('EEF', NULL, 'Estonia - Air Force'),
       ('EZZ', 'LI', 'ETF Airways'),
       ('ETD', 'EY', 'Etihad Airways'),
       ('EAK', '5B', 'Euro-Asia Air'),
       ('SEB', NULL, 'Euroavia Airlines'),
       ('BUC', 'H6', 'European Air Charter'),
       ('PGC', NULL, 'European Aircraft Private Club'),
       ('PTO', NULL, 'European Flight Academy'),
       ('FYS', NULL, 'European Flyers'),
       ('EWG', 'EW', 'Eurowings'),
       ('EVA', 'BR', 'EVA Air'),
       ('EWR', 'ZD', 'EWA Air'),
       ('REE', NULL, 'Exclusive Aviation'),
       ('EJO', NULL, 'Execujet Middle East'),
       ('ENK', NULL, 'Executive Airlink'),
       ('EXJ', NULL, 'Executive Jet Charter'),
       ('EVS', '8K', 'Exploits Valley Air Services'),
       ('EFA', 'QE', 'Express Freighters Australia'),
       ('EZA', 'MG', 'Eznis Airways'),
       ('IFA', NULL, 'FAI rent-a-jet'),
       ('FJE', '7F', 'Fanjet Express'),
       ('PBR', NULL, 'Fast Air'),
       ('FDR', 'C8', 'Federal Air'),
       ('FNX', NULL, 'Fenix Air Charter'),
       ('FJI', 'FJ', 'Fiji Airways'),
       ('FTR', NULL, 'Finistair'),
       ('FNG', NULL, 'Finland - Border Guard'),
       ('FIH', NULL, 'FinnHEMS'),
       ('FAB', '7F', 'First Air'),
       ('EXV', '8D', 'FitsAir'),
       ('FRF', NULL, 'Fleet Air International'),
       ('LXJ', NULL, 'Flexjet'),
       ('FJO', NULL, 'Flexjet Operations Malta'),
       ('VOR', NULL, 'Flight Calibration Services'),
       ('OPT', NULL, 'Flight options'),
       ('FEX', NULL, 'FlightExec'),
       ('FLZ', 'YS', 'Flightlink'),
       ('FWK', NULL, 'Flightworks'),
       ('FFY', NULL, 'Florida Flyers Flight Academy'),
       ('FXI', 'NY', 'Flugfelag Islands'),
       ('ACW', NULL, 'Fly Across'),
       ('KPO', NULL, 'Fly Alliance'),
       ('ALW', NULL, 'Fly ALS'),
       ('FBA', 'IF', 'Fly Baghdad'),
       ('FJK', NULL, 'Fly Jet KZ'),
       ('FKH', 'D3', 'Fly Khiva'),
       ('PVV', 'FP', 'Fly Pro'),
       ('FSQ', NULL, 'Fly Sky Airlines'),
       ('FTY', NULL, 'Fly Tyrol'),
       ('FCA', NULL, 'Fly-Coop Air Service'),
       ('FFA', 'F4', 'Fly4 Airlines'),
       ('GOA', 'IC', 'Fly91'),
       ('AYN', 'FS', 'FlyArystan'),
       ('FBZ', 'FO', 'Flybondi'),
       ('FEG', 'FT', 'FlyEgypt'),
       ('TOR', 'SX', 'FlyGTA Airlines'),
       ('FYG', NULL, 'Flying Service'),
       ('FJL', '9P', 'FlyJinnah'),
       ('VQI', 'VP', 'FlyMe'),
       ('FLN', 'WV', 'FlyNamibia'),
       ('FIA', '5F', 'FlyOne'),
       ('FOE', 'OE', 'FlyOne Romania'),
       ('SFR', 'FA', 'FlySafair'),
       ('PYN', NULL, 'FlyWales'),
       ('ULA', NULL, 'Four Corners Aviation'),
       ('POF', NULL, 'France - \tPolice Aux Frontiers'),
       ('CTM', NULL, 'France - Air Forces Command'),
       ('FDO', NULL, 'France - Customs'),
       ('FRU', NULL, 'France - Securite Civile'),
       ('FHY', 'FH', 'Freebird Airlines'),
       ('FDT', '4F', 'Freedom Airline Express'),
       ('FRG', NULL, 'Freight Runners Express'),
       ('FFT', 'F9', 'Frontier'),
       ('FGO', 'C0', 'FTL Airlines'),
       ('FZA', 'FU', 'Fuzhou Airlines'),
       ('GNJ', NULL, 'GainJet'),
       ('GMA', NULL, 'Gama Aviation'),
       ('GSH', NULL, 'Gama Aviation UAE'),
       ('GZP', '4G', 'Gazpromavia'),
       ('GLX', NULL, 'Gelix Airlines'),
       ('GNX', NULL, 'Genex'),
       ('IGT', 'GH', 'Georgian Airlines'),
       ('AUG', NULL, 'Georgian Aviation University'),
       ('GER', 'ZQ', 'German Airways'),
       ('CHX', NULL, 'Germany - Air Ambulance'),
       ('GAM', NULL, 'Germany - Army'),
       ('GNY', NULL, 'Germany - Navy'),
       ('GES', NULL, 'Gestair'),
       ('GJT', 'GW', 'Getjet Airlines'),
       ('GMS', 'NJ', 'Ghadames Air Transport'),
       ('GJE', NULL, 'Global Air Charters'),
       ('GBL', NULL, 'Global Airways'),
       ('GBF', NULL, 'Global Aviation Burkina Faso'),
       ('SVW', NULL, 'Global Jet Luxembourg'),
       ('GWW', NULL, 'Global Wings'),
       ('GAC', NULL, 'GlobeAir'),
       ('GYS', NULL, 'Go Jet Aviation'),
       ('GJS', 'G7', 'GoJet '),
       ('GDK', NULL, 'Goldeck Flug'),
       ('GPX', 'IV', 'GP Aviation'),
       ('CVU', 'YR', 'Grand Canyon Airlines'),
       ('GUN', 'GV', 'Grant Aviation'),
       ('HAF', NULL, 'Greece - Air Force'),
       ('HNA', NULL, 'Greece - Navy'),
       ('GAG', NULL, 'Greybird Aviation'),
       ('GTX', NULL, 'GTA Air'),
       ('TSU', 'IF', 'Gulf and Caribbean Cargo'),
       ('GBG', 'G2', 'GullivAir'),
       ('GUA', NULL, 'Guna Airlines'),
       ('HHN', 'HR', 'Hahn Air'),
       ('CHH', 'HU', 'Hainan Airlines'),
       ('HGA', NULL, 'Halla Airlines'),
       ('HSF', NULL, 'Hanseo University'),
       ('BOM', NULL, 'Haute Aviation'),
       ('HAL', 'HA', 'Hawaiian Airlines'),
       ('HBH', 'NS', 'Hebei Airlines'),
       ('HLR', NULL, 'Heli Air Services'),
       ('HLI', NULL, 'Heli Securite'),
       ('HLU', NULL, 'H\u00e9li-Union'),
       ('HDB', NULL, 'HeliDubai'),
       ('HTS', NULL, 'Helistar'),
       ('HDR', NULL, 'Helitrans'),
       ('HLJ', 'H3', 'Hello Jets'),
       ('HGH', NULL, 'Henley Air'),
       ('HRM', 'H3', 'Hermes Airlines'),
       ('HST', 'HN', 'Heston Airlines'),
       ('HFM', '3L', 'Hi Fly Malta'),
       ('HND', 'OI', 'Hinterland Aviation'),
       ('HYS', 'H4', 'HiSky Europe'),
       ('HNZ', NULL, 'HNV Cote d''Ivoire'),
       ('HES', '5Q', 'Holiday Europe'),
       ('HKC', 'RH', 'Hong Kong Air Cargo'),
       ('HPJ', NULL, 'Hop-A-Jet'),
       ('HOV', NULL, 'Hoverfly'),
       ('ETI', NULL, 'Hummingbird Aviation'),
       ('MML', 'MR', 'Hunnu Air'),
       ('HYP', NULL, 'Hyperion Aviation'),
       ('IFY', NULL, 'I-Fly Air'),
       ('MMY', NULL, 'IASCO Flight Training'),
       ('IBE', 'IB', 'Iberia'),
       ('EVE', 'E9', 'Iberojet'),
       ('IAN', 'QI', 'Ibom Air'),
       ('ICG', NULL, 'Iceland - Coast Guard'),
       ('ICF', NULL, 'ICS-Aero'),
       ('KAR', 'EO', 'Ikar'),
       ('JTI', NULL, 'ImperialJet'),
       ('ISU', NULL, 'Indiana State University'),
       ('IGO', '6E', 'IndiGo'),
       ('INI', NULL, 'Initium Aviation'),
       ('ITI', NULL, 'iNTAIRLINE'),
       ('HGT', NULL, 'Intel Air Shuttle'),
       ('IJW', 'K8', 'InterJet West'),
       ('RED', NULL, 'International Committee of the Red Cross'),
       ('IAE', 'IO', 'IrAero'),
       ('IRB', 'B9', 'Iran Airtour'),
       ('IGC', NULL, 'Iraq Gate Company'),
       ('KCE', NULL, 'Irving Oil Transport'),
       ('ISR', '6H', 'Israir Airlines'),
       ('ITL', NULL, 'Italfly'),
       ('IEI', NULL, 'Italy - Army'),
       ('MMI', NULL, 'Italy - Navy'),
       ('IZA', 'I8', 'Izhavia'),
       ('LTD', NULL, 'JA Air Charter'),
       ('JMA', 'JM', 'Jambojet'),
       ('JAL', 'JL', 'Japan Airlines'),
       ('JWD', NULL, 'Jayawijaya Dirgantara'),
       ('JZA', 'QK', 'Jazz Aviation'),
       ('JJA', '7C', 'Jeju Air'),
       ('PJS', 'PP', 'Jet Aviation Business Jets'),
       ('JBD', NULL, 'Jet Aviation Business Jets Deutschland'),
       ('JCT', 'N2', 'Jet Charter'),
       ('EDG', NULL, 'Jet Edge'),
       ('JFL', NULL, 'Jet Fly Airline'),
       ('JTL', 'JL', 'Jet Linx Aviation'),
       ('JNS', NULL, 'Jet Net Services'),
       ('JTK', 'JK', 'Jet Sky Airways'),
       ('JTN', NULL, 'Jet Test International'),
       ('EXS', 'LS', 'Jet2'),
       ('JBU', 'B6', 'JetBlue'),
       ('QNZ', NULL, 'Jetconnect'),
       ('JFA', NULL, 'Jetfly Aviation'),
       ('JKH', NULL, 'Jetkontor'),
       ('JNL', NULL, 'JetNetherlands'),
       ('JTY', NULL, 'Jetology'),
       ('CEO', NULL, 'Jetset'),
       ('JES', 'WJ', 'JetSMART Argentina'),
       ('JAP', 'JZ', 'JetSMART Peru'),
       ('JST', 'JQ', 'Jetstar'),
       ('JJP', 'GK', 'Jetstar Japan'),
       ('VTB', NULL, 'JetStream Charter'),
       ('JTD', 'JP', 'Jettime'),
       ('JLB', NULL, 'Jhonlin Air Transport'),
       ('CJX', 'RY', 'Jiangxi Air'),
       ('JNA', 'LJ', 'Jin Air'),
       ('JIV', NULL, 'Jivair'),
       ('JON', NULL, 'Jonair'),
       ('RJZ', NULL, 'Jordan - Air Force'),
       ('JNY', NULL, 'Journey Aviation'),
       ('JSM', NULL, 'JS Aviation'),
       ('JSX', 'XE', 'JSX'),
       ('JUP', NULL, 'Jump Air'),
       ('JSY', NULL, 'Jung Sky'),
       ('KMI', '8K', 'K-Mile Air'),
       ('KAI', NULL, 'KaiserAir'),
       ('KFS', 'K9', 'Kalitta Charters'),
       ('KMF', 'RQ', 'Kam Air'),
       ('KAE', NULL, 'Kangala Air Express'),
       ('KRU', NULL, 'Karun Airlines'),
       ('KFA', 'FK', 'Kelowna Flightcraft Air'),
       ('KEN', 'M5', 'Kenmore Air'),
       ('KSF', NULL, 'Kent State University'),
       ('KEY', NULL, 'Key Air'),
       ('KHF', NULL, 'KhabAvia'),
       ('KIS', NULL, 'Kish Air'),
       ('KLM', 'KL', 'KLM'),
       ('KMM', 'KM', 'KM Malta Airlines'),
       ('KMA', 'KO', 'Komiaviatrans'),
       ('KAG', NULL, 'Korea Aviation College'),
       ('KTU', NULL, 'Korea National University of Transportation'),
       ('KAL', 'KE', 'Korean Air'),
       ('SSJ', 'KV', 'Krasavia'),
       ('KNA', 'KY', 'Kunming Airlines'),
       ('WCD', NULL, 'Kyungwoon University'),
       ('LFA', NULL, 'L3Harris Airline Academy'),
       ('NIS', 'LC', 'La Costena'),
       ('LAM', 'TM', 'LAM'),
       ('LLL', 'LK', 'Lao Skyway'),
       ('LER', 'QL', 'Laser Airlines'),
       ('TAM', 'JJ', 'LATAM Brasil'),
       ('LTG', 'M3', 'LATAM Cargo Brasil'),
       ('LXP', 'LU', 'LATAM Chile'),
       ('LNE', 'XL', 'LATAM Ecuador'),
       ('LPE', 'LP', 'LATAM Peru'),
       ('LDA', 'LW', 'Lauda Europe'),
       ('NGN', 'KK', 'LEAV Aviation'),
       ('LAL', 'LZ', 'Legend Airlines'),
       ('LVL', NULL, 'Level'),
       ('LAA', 'LN', 'Libyan Airlines'),
       ('LWA', 'YL', 'Libyan Wings'),
       ('LLK', NULL, 'Life Line Aviation'),
       ('LNI', 'JT', 'Lion Air'),
       ('LIP', '8I', 'Lipican Aer'),
       ('LAZ', 'L0', 'Liz Aviation'),
       ('LOG', 'LM', 'Loganair'),
       ('SNG', 'LT', 'LongJiang Airlines'),
       ('CDC', 'GJ', 'Loong Air'),
       ('LKE', '8L', 'Lucky Air'),
       ('GEC', NULL, 'Lufthansa Cargo'),
       ('CLH', 'CL', 'Lufthansa CityLine'),
       ('LWI', 'L9', 'Lumiwings'),
       ('LGL', 'LG', 'Luxair'),
       ('AAB', NULL, 'Luxaviation Belgium'),
       ('LXG', NULL, 'Luxaviation Germany'),
       ('LRQ', NULL, 'Luxembourg Air Ambulance'),
       ('LYD', NULL, 'Lydd Air'),
       ('MEN', 'MA', 'MAE Aircraft Management'),
       ('GMT', 'UJ', 'Magnicharters'),
       ('WMA', NULL, 'Makers Air'),
       ('RMF', NULL, 'Malaysia - Air Force'),
       ('DQA', 'Q2', 'Maldivian'),
       ('MAE', NULL, 'Mali Air'),
       ('MMO', 'MT', 'Malta MedAir'),
       ('MDA', 'AE', 'Mandarin Airlines'),
       ('MAV', 'NR', 'Manta Air'),
       ('MBU', 'DI', 'Marabu'),
       ('MPH', 'MP', 'Martinair Holland'),
       ('MAA', 'M7', 'mas'),
       ('MWG', 'MY', 'MASwings'),
       ('MAI', 'L6', 'Mauritania Airlines International'),
       ('NGL', 'VM', 'Max Air'),
       ('MAX', NULL, 'Max Aviation'),
       ('MXM', '6M', 'Maximus Airlines'),
       ('MKL', NULL, 'McCall Aviation'),
       ('MEA', 'ME', 'MEA'),
       ('MDM', NULL, 'Medavia'),
       ('MNS', 'BM', 'Medsky Airways'),
       ('MRJ', NULL, 'Meraj Airlines'),
       ('MEM', NULL, 'Meridian'),
       ('MZY', NULL, 'Mermoz-Academy'),
       ('MXA', 'XN', 'Mexicana'),
       ('FAM', NULL, 'Mexico - Air Force'),
       ('ANX', NULL, 'Mexico - Navy'),
       ('MGD', NULL, 'Miami Air Lease'),
       ('MFG', NULL, 'Mid Africa Aviation'),
       ('NIT', NULL, 'Middle Georgia State University'),
       ('DZR', NULL, 'Midwest Aviation'),
       ('MIM', NULL, 'Millesime Aviation'),
       ('MJF', NULL, 'MJet'),
       ('AMA', NULL, 'Moalem Aviation'),
       ('MWM', 'WD', 'Modern Logistics'),
       ('MGW', 'XF', 'Mongolian Airways'),
       ('MSI', 'M9', 'Motor Sich Airlines'),
       ('FTH', NULL, 'Mountain Aviation'),
       ('MVE', NULL, 'Move'),
       ('MFX', 'C6', 'My Freighter'),
       ('MYJ', NULL, 'My Jet'),
       ('MMA', '8M', 'Myanmar Airways International'),
       ('MYW', 'MJ', 'MyWay Airlines'),
       ('LKN', 'IN', 'Nam Air'),
       ('ACK', NULL, 'Nantucket Airlines'),
       ('NCR', 'N8', 'National Airlines'),
       ('NTN', NULL, 'National Airways Corporation'),
       ('QJE', NULL, 'National Jet Systems'),
       ('RON', 'ON', 'Nauru Airlines'),
       ('NOS', 'NO', 'Neos'),
       ('NMA', 'NE', 'Nesma Airlines'),
       ('NRN', NULL, 'Netherlands - Navy'),
       ('EJA', NULL, 'NetJets'),
       ('NJU', NULL, 'Netjets UK'),
       ('NEA', 'EJ', 'New England Airlines'),
       ('RVF', '7H', 'New Pacific Airlines'),
       ('NWY', 'NU', 'New Way Cargo Airlines'),
       ('KIW', NULL, 'New Zealand - Royal New Zealand Air Force'),
       ('XLE', '2N', 'NG Eagle'),
       ('NHD', NULL, 'NHV'),
       ('JTZ', NULL, 'Nicholas Air'),
       ('NGR', NULL, 'Nigeria - Air Force'),
       ('NCA', 'KZ', 'Nippon Cargo Airlines'),
       ('NOK', 'DD', 'Nok Air'),
       ('NUM', NULL, 'Nomad Aviation'),
       ('NHX', NULL, 'Noordzee Helikopters Vlaanderen'),
       ('NDA', 'ND', 'Nordica'),
       ('NWS', 'N4', 'Nordwind Airlines'),
       ('FCM', 'N7', 'NORRA'),
       ('UBT', 'Z0', 'Norse UK'),
       ('NCB', NULL, 'North Cariboo Air'),
       ('NFA', NULL, 'North Flying'),
       ('NWC', '0E', 'North-West Air Company'),
       ('CNW', 'CO', 'North-Western Cargo International Airlines'),
       ('NEW', NULL, 'Northeastern Aviation Corporation'),
       ('NAC', 'NC', 'Northern Air Cargo'),
       ('NTA', NULL, 'Northern Thunderbird Air'),
       ('NWF', NULL, 'Northwest Flyers'),
       ('NOW', NULL, 'Norway - Air Force'),
       ('NSZ', 'D8', 'Norwegian Air Sweden'),
       ('NOV', NULL, 'Nova Airways'),
       ('NOJ', NULL, 'NovaJet'),
       ('NYX', 'OJ', 'Nyxair'),
       ('OSU', NULL, 'Ohio State University'),
       ('OKA', 'BK', 'Okay Airways'),
       ('OAL', 'OA', 'Olympic Air'),
       ('MJN', NULL, 'Oman - Royal Air Force'),
       ('OAE', 'OY', 'Omni Air International'),
       ('OAV', NULL, 'Omni Aviation'),
       ('HGO', 'HC', 'One Air'),
       ('OBS', '6O', 'Orbest'),
       ('OGN', 'OG', 'Origin Air'),
       ('ORT', NULL, 'Ortac'),
       ('SCQ', NULL, 'OSM Aviation Academy'),
       ('OLA', 'OF', 'Overland Airways'),
       ('OYO', NULL, 'Oyonnair'),
       ('WIS', NULL, 'Paccair'),
       ('PCO', '8P', 'Pacific Coastal Airlines'),
       ('PIA', 'PK', 'Pakistan International Airlines'),
       ('PVL', 'PB', 'PAL Airlines'),
       ('PXC', 'P9', 'Palau Express Airlines'),
       ('EUP', NULL, 'Pan Europeenne'),
       ('VPC', NULL, 'Panaviatic'),
       ('UZP', '5P', 'Panorama Airways'),
       ('AZP', 'ZP', 'Paranair'),
       ('DIG', 'OP', 'PassionAir'),
       ('PPT', NULL, 'Patria Pilot Training'),
       ('PTW', NULL, 'Pattaya Airways'),
       ('APJ', 'MM', 'Peach'),
       ('PEG', NULL, 'Pegasus Elite Aviation'),
       ('PAS', 'IP', 'Pelita Air'),
       ('PRZ', NULL, 'Performance Air'),
       ('FPR', NULL, 'Peru - Air Force'),
       ('PER', 'UF', 'Petroleum Air Service'),
       ('PHM', NULL, 'PHI'),
       ('APG', 'Z2', 'Philippines AirAsia'),
       ('GRB', 'PH', 'Phoenix Air'),
       ('PDT', 'PT', 'Piedmont Airlines'),
       ('PIP', NULL, 'Pilot Flight Academy'),
       ('SOW', NULL, 'Pink Sparrow'),
       ('PXR', NULL, 'PixAir Survey'),
       ('PMS', NULL, 'Planemaster Services'),
       ('PVA', NULL, 'Planet 9'),
       ('FPY', 'OG', 'Play'),
       ('TOK', 'BV', 'Toki Air'),
       ('PLF', NULL, 'Poland - Air Force'),
       ('PAC', 'PO', 'Polar Air Cargo'),
       ('LPR', NULL, 'Polish Medical Air Rescue'),
       ('PTR', 'P3', 'Porter'),
       ('AFP', NULL, 'Portugal - Air Force'),
       ('PON', NULL, 'Portugal - Navy'),
       ('MSA', 'M4', 'Poste Air Cargo'),
       ('PWC', NULL, 'Pratt and Whitney'),
       ('PRE', NULL, 'Precision Aircraft Management'),
       ('MVP', NULL, 'Premier Private Jets'),
       ('PWA', NULL, 'Priester Aviation'),
       ('PNC', NULL, 'Prince Aviation'),
       ('PVO', NULL, 'Privaira'),
       ('OKC', NULL, 'Private Jets'),
       ('PVG', 'P6', 'Privilege Style'),
       ('PFZ', 'P0', 'Proflight Zambia'),
       ('JIA', 'OH', 'PSA Airlines'),
       ('QAV', NULL, 'QA Aviation'),
       ('QFA', 'QF', 'Qantas'),
       ('QAF', NULL, 'Qatar - Amiri Flight'),
       ('QQE', 'QE', 'Qatar Executive'),
       ('QAZ', 'IQ', 'Qazaq Air'),
       ('EIS', NULL, 'QinetiQ'),
       ('QDA', 'QW', 'Qingdao Airlines'),
       ('QJT', NULL, 'Qingdao Jiutian International Flight Academy'),
       ('LBQ', NULL, 'Quest Diagnostics'),
       ('FQA', 'QO', 'Quikjet Cargo Airlines'),
       ('RBF', 'R0', 'Raindo United Service'),
       ('RAN', 'R4', 'Rano Air'),
       ('RMY', 'TH', 'Raya Airways'),
       ('RLT', NULL, 'Real Tonga Airline'),
       ('RTO', NULL, 'Rectimo Air Transports'),
       ('REA', 'L5', 'Red Air'),
       ('LAK', NULL, 'Red Wing Aviation'),
       ('BXR', NULL, 'Redding Aero Enterprises'),
       ('RVV', NULL, 'Reeve Air Alaska'),
       ('RGA', NULL, 'REGA Swiss Air-Rescue'),
       ('REG', '8N', 'Regional Air Services'),
       ('RLI', NULL, 'Reliant Air'),
       ('RNI', NULL, 'Rennia Aviation'),
       ('FRV', NULL, 'Revv Aviation'),
       ('RGM', NULL, 'RGA-Black Stone Airlines'),
       ('RCA', NULL, 'Richland Aviation'),
       ('OEY', 'RI', 'Rimbun Air'),
       ('RXI', NULL, 'Riyadh Air'),
       ('RCR', 'NJ', 'ROMCargo Airlines'),
       ('REM', NULL, 'Rose Air'),
       ('RJD', 'RG', 'Rotana Jet'),
       ('RAM', 'AT', 'Royal Air Maroc'),
       ('RJA', 'RJ', 'Royal Jordanian'),
       ('RYL', 'RW', 'Royalair Philippines'),
       ('RSB', NULL, 'Rubystar'),
       ('RSJ', NULL, 'RusJet'),
       ('CHD', NULL, 'Russia - 223rd Flight Unit State Airline'),
       ('RFF', NULL, 'Russia - Air Force'),
       ('SUM', NULL, 'Russia - Ministry of Emergency Situations (MChS)'),
       ('RSD', NULL, 'Russia - Special Flight Squadron'),
       ('REV', NULL, 'RVL Aviation'),
       ('RWL', NULL, 'RWL German Flight Academy'),
       ('RYR', 'FR', 'Ryanair'),
       ('SBI', 'S7', 'S7 Airlines'),
       ('SCT', NULL, 'SAAB Aircraft'),
       ('SHP', NULL, 'SAF Helicopteres'),
       ('XLK', 'F2', 'Safarilink Aviation'),
       ('SAO', NULL, 'Sahel Aviation Service'),
       ('OMS', 'OV', 'SalamAir'),
       ('SDP', NULL, 'Sama Airline'),
       ('SMF', NULL, 'San Marino Executive Aviation'),
       ('KGB', 'S2', 'Sapsan Airline'),
       ('SAS', 'SK', 'SAS'),
       ('SVS', NULL, 'SAS Link'),
       ('NSE', '9R', 'Satena'),
       ('SRA', NULL, 'Saudi Arabia - Royal Flight'),
       ('SAU', NULL, 'Saurya Airlines'),
       ('SXN', NULL, 'SaxonAir'),
       ('ABF', NULL, 'Scanwings'),
       ('SAB', NULL, 'Schmiedel Air Service'),
       ('SBS', 'BB', 'Seaborne'),
       ('SRC', NULL, 'Searca'),
       ('JSL', NULL, 'SelectJet'),
       ('SRB', NULL, 'Serbia - Air Force'),
       ('ENL', NULL, 'Servicios Optimos de Aeroenlace'),
       ('RVP', NULL, 'Sevenair'),
       ('CSS', 'O3', 'SF Airlines'),
       ('CDG', 'SC', 'Shandong Airlines'),
       ('RXF', NULL, 'Shandong Dagao International Flight Academy'),
       ('CSH', 'FM', 'Shanghai Airlines'),
       ('CSZ', 'ZH', 'Shenzhen Airlines'),
       ('SHA', 'N9', 'Shree Airlines'),
       ('SGN', '5E', 'Siam General Aviation'),
       ('SID', NULL, 'Sideral Linhas Aereas'),
       ('SPA', 'SI', 'Sierra Pacific Airlines'),
       ('SUA', NULL, 'Silesia Air'),
       ('AZG', '7L', 'Silk Way West Airlines'),
       ('SIS', NULL, 'Silver Air'),
       ('SIL', '3M', 'Silver Airways'),
       ('SLH', NULL, 'Silverhawk Aviation'),
       ('SIA', 'SQ', 'Singapore Airlines'),
       ('SJM', NULL, 'Sino Jet'),
       ('SIO', NULL, 'Sirio'),
       ('SIU', NULL, 'Sirius Airlines'),
       ('SKU', 'H2', 'Sky Airline'),
       ('SWM', 'ZA', 'Sky Angkor Airlines'),
       ('SNA', 'RD', 'Sky Cana'),
       ('KGZ', NULL, 'Sky Fru'),
       ('LIZ', 'DU', 'Sky Jet M.G.'),
       ('KYE', 'GG', 'Sky Lease Cargo'),
       ('SPD', NULL, 'Sky Prime Aviation'),
       ('HHK', 'A7', 'Sky Shuttle Helicopters'),
       ('SWU', 'BQ', 'SkyAlps'),
       ('IOS', NULL, 'Skybus'),
       ('EMO', NULL, 'Skyemotion'),
       ('SHH', 'DO', 'SKYhigh Dominicana'),
       ('UTN', 'QU', 'Skyline Express'),
       ('SKY', 'BC', 'Skymark Airlines'),
       ('EAN', 'NV', 'Skypower Express Airways'),
       ('SKV', NULL, 'Skyside'),
       ('TTQ', NULL, 'Skytrack Systems'),
       ('SQP', 'PQ', 'SkyUp Airlines'),
       ('DYN', '4A', 'Skyvalue Airways'),
       ('SKZ', NULL, 'Skyway Enterprises'),
       ('SCW', 'CW', 'SkyWest Charter'),
       ('SLN', NULL, 'Sloane Helicopters'),
       ('SSG', NULL, 'Slovakia - Government'),
       ('GSI', NULL, 'Slovenia - Government'),
       ('SME', NULL, 'Smart Aviation'),
       ('SJI', NULL, 'Smart Jet International'),
       ('SMG', NULL, 'Smartline'),
       ('MYX', NULL, 'SmartLynx Estonia'),
       ('TVS', 'QS', 'Smartwings'),
       ('TVP', '3Z', 'Smartwings Poland'),
       ('TWY', NULL, 'Solairus Aviation'),
       ('SET', NULL, 'Solenta Aviation'),
       ('SVG', NULL, 'Solenta Aviation Gabon'),
       ('SOL', 'IE', 'Solomon Airlines'),
       ('SMR', 'SZ', 'Somon Air'),
       ('LMG', NULL, 'South Africa - Air Force'),
       ('SOA', 'PL', 'Southern Air Charter'),
       ('SXI', NULL, 'Southern Cross International'),
       ('SWA', 'WN', 'Southwest Airlines'),
       ('AME', NULL, 'Spain - Air Force'),
       ('SSM', NULL, 'Spain - Coast Guard'),
       ('DGP', NULL, 'Spain - National Police'),
       ('QFX', NULL, 'Sparfell Malta'),
       ('SCU', NULL, 'Spartan College of Aeronautics and Technology'),
       ('SEJ', 'SG', 'SpiceJet'),
       ('SJJ', NULL, 'SpiritJets'),
       ('CQH', '9C', 'Spring Airlines'),
       ('SRN', 'P8', 'SprintAir'),
       ('QSR', NULL, 'SR Jet'),
       ('SJY', 'SJ', 'Sriwijaya Air'),
       ('STB', 'LE', 'St Barth Executive'),
       ('SDG', 'S5', 'Star Air'),
       ('SEK', '4R', 'Star East Airlines'),
       ('SRU', '2I', 'Star Peru'),
       ('SWP', NULL, 'Star Work Sky'),
       ('XSK', NULL, 'Stark Airways'),
       ('TRL', NULL, 'Starlite Aviation'),
       ('SRY', 'VC', 'Sterling Airways'),
       ('STP', '8F', 'STP Airways'),
       ('SUB', NULL, 'Suburban Air Freight'),
       ('SUT', NULL, 'Summit Air'),
       ('SAV', NULL, 'Sun Air'),
       ('SCX', 'SY', 'Sun Country Airlines'),
       ('VKG', 'DK', 'Sunclass Airlines'),
       ('SDR', 'SR', 'Sundair'),
       ('MDT', NULL, 'Sundt Air'),
       ('BBK', NULL, 'Sunkar Air'),
       ('KSZ', 'S6', 'Sunrise Airways'),
       ('CNK', NULL, 'Sunwest Aviation'),
       ('YZR', 'Y8', 'Suparna Airlines'),
       ('NPG', 'P7', 'Supernova Airlines'),
       ('SLM', 'PY', 'Surinam Airways'),
       ('SQS', NULL, 'Susi Air'),
       ('SWV', NULL, 'Svensk Luftambulans'),
       ('JET', NULL, 'Svenskt Industriflyg'),
       ('SVF', NULL, 'Sweden - Armed Forces'),
       ('POL', NULL, 'Sweden - Police'),
       ('WFC', NULL, 'Swift Copters'),
       ('MDF', NULL, 'Swiftair Hellas'),
       ('SFS', NULL, 'Swiss Flight Services'),
       ('SWW', NULL, 'Swiss Private Jet'),
       ('SXM', NULL, 'SXM Airways'),
       ('SYN', NULL, 'Syncrude Canada'),
       ('SYR', 'RB', 'Syrian Air'),
       ('DTA', 'DT', 'TAAG Angola Airlines'),
       ('TBN', NULL, 'Taban Airlines'),
       ('TBJ', NULL, 'TAG Aviation Asia'),
       ('TEU', NULL, 'TAG Aviation Malta'),
       ('TGU', '5U', 'TagAirlines'),
       ('TWI', 'TI', 'Tailwind Airlines'),
       ('TFF', NULL, 'Talon Air'),
       ('TAP', 'TP', 'TAP Air Portugal'),
       ('LCT', 'YQ', 'TAR Aerolineas'),
       ('ROT', 'RO', 'Tarom'),
       ('TMN', 'HJ', 'Tasman Cargo Airlines'),
       ('TTJ', NULL, 'Tatra JET'),
       ('TZS', 'N6', 'TCA'),
       ('VLY', NULL, 'Tennessee Valley Authority'),
       ('XLR', NULL, 'Texel Air'),
       ('TEZ', 'K9', 'Tez Jet Airlines'),
       ('TAX', 'XJ', 'Thai AirAsia X'),
       ('TLM', 'SL', 'Thai Lion Air'),
       ('TLJ', NULL, 'Thalair'),
       ('LJC', NULL, 'The Little Jet Company'),
       ('TIV', NULL, 'Thrive'),
       ('THU', NULL, 'Thunder Airlines'),
       ('GCR', 'GS', 'Tianjin Airlines'),
       ('TTW', 'IT', 'Tigerair Taiwan'),
       ('NAD', NULL, 'Tinadar Jets'),
       ('TMT', 'TM', 'Titan Airways Malta'),
       ('TTL', '0T', 'Total Linhas Aereas'),
       ('TDR', 'C3', 'Trade Air'),
       ('TSG', 'Q8', 'Trans Air Congo'),
       ('TGY', NULL, 'Trans Guyana Airways'),
       ('TMW', NULL, 'Trans Maldivian Airways'),
       ('MUI', 'R9', 'Transair'),
       ('TVF', 'TO', 'Transavia France'),
       ('TXC', NULL, 'Transaviaexport Airlines'),
       ('TMC', NULL, 'Travel Management Company'),
       ('AOO', NULL, 'Trebet Aviation'),
       ('WMN', NULL, 'Trident Aircraft'),
       ('TOS', '9N', 'Tropic Air'),
       ('TDS', 'TZ', 'Tsaradia'),
       ('TFL', 'OR', 'TUI Airlines Netherlands'),
       ('TUI', 'X3', 'TUI fly'),
       ('RFE', NULL, 'Tulpar'),
       ('TAR', 'TU', 'Tunisair'),
       ('TUN', NULL, 'Tunisia - Air Force'),
       ('TRK', NULL, 'Turkey - Government'),
       ('TUG', NULL, 'Turkmenistan - Government'),
       ('VTU', 'T9', 'Turpial Airlines'),
       ('TJT', 'T7', 'Twin Jet'),
       ('TJS', NULL, 'Tyrolean Jets & Services'),
       ('UGJ', NULL, 'UG Jet'),
       ('UTS', NULL, 'Ukraine - State Air Traffic Service'),
       ('AUI', 'PS', 'Ukraine International Airlines'),
       ('KZU', 'GO', 'ULS Airlines Cargo'),
       ('UMZ', NULL, 'UmzaXpress'),
       ('UIA', 'B7', 'UNI Air'),
       ('UFX', NULL, 'Uni-Fly Heliworx'),
       ('UNI', NULL, 'Unicair'),
       ('UQA', NULL, 'Unique Air'),
       ('UAF', NULL, 'United Arab Emirates - Air Force'),
       ('UEE', NULL, 'United Eagle'),
       ('AAC', NULL, 'United Kingdom - Army Air Corps'),
       ('SRD', NULL, 'United Kingdom - Coast Guard'),
       ('SRG', NULL, 'United Kingdom - Maritime and Coastguard Agency'),
       ('SHF', NULL, 'United Kingdom - RAF Support Helicopter Force'),
       ('WTN', NULL, 'United Kingdom - RAF Warton Military Flight Ops'),
       ('RFR', NULL, 'United Kingdom - Royal Air Force'),
       ('RRR', NULL, 'United Kingdom - Royal Air Force Air Transport'),
       ('NVY', NULL, 'United Kingdom - Royal Navy'),
       ('UNO', NULL, 'United Nations'),
       ('RCH', NULL, 'United States - Air Force'),
       ('CFR', NULL, 'United States - California Department of Forestry'),
       ('IGY', NULL, 'United States - NASA'),
       ('DOI', NULL, 'United States - US Department of Interior'),
       ('DOJ', NULL, 'United States - US Department of Justice'),
       ('DOS', NULL, 'United States - US Department of State'),
       ('XCN', NULL, 'United States - US Forest Service'),
       ('RPN', NULL, 'United States - US Immigration and Customs Enforcement'),
       ('UVL', 'VO', 'Universal Air'),
       ('OUA', NULL, 'University of Oklahoma'),
       ('UPS', '5X', 'UPS'),
       ('SVR', 'U6', 'Ural Airlines'),
       ('UBG', 'BS', 'US-Bangla Airlines'),
       ('USY', 'XG', 'USC'),
       ('UVT', 'RT', 'UVT Aero'),
       ('VVV', NULL, 'Valair'),
       ('VLJ', NULL, 'VallJet'),
       ('VAA', 'V9', 'Van Air Europe'),
       ('VFC', '0V', 'Vasco'),
       ('VNT', NULL, 'Ventura'),
       ('VWA', NULL, 'Venture West'),
       ('VID', NULL, 'Via Air'),
       ('VES', 'V4', 'Vieques Air Link'),
       ('HVN', 'VN', 'Vietnam Airlines'),
       ('VIR', 'VS', 'Virgin Atlantic'),
       ('VOZ', 'VA', 'Virgin Australia'),
       ('VJA', NULL, 'Vista America'),
       ('VJH', 'H5', 'VistaJet'),
       ('VIV', 'VB', 'VivaAerobus'),
       ('VLZ', NULL, 'Volare Aviation'),
       ('VOC', 'Q6', 'Volaris Costa Rica'),
       ('TMB', NULL, 'Volato'),
       ('VOE', 'V7', 'Volotea'),
       ('VRG', NULL, 'Voyage Air'),
       ('VLG', 'VY', 'Vueling'),
       ('PLM', 'EB', 'Wamos Air'),
       ('WSG', 'WP', 'Wasaya Airways'),
       ('BLW', NULL, 'Wermlandsflyg'),
       ('PCM', NULL, 'West Air'),
       ('NPT', NULL, 'West Atlantic'),
       ('WLN', NULL, 'West Link Airlines'),
       ('WSH', NULL, 'Westair Helicopter Saudi'),
       ('WAE', NULL, 'Western Air Express'),
       ('WGN', 'KD', 'Western Global Airlines'),
       ('WMU', NULL, 'Western Michigan University College of Aviation'),
       ('WJA', 'WS', 'WestJet'),
       ('WUP', NULL, 'Wheels Up'),
       ('WIF', 'WF', 'Wideroe'),
       ('WHS', NULL, 'Wiking Helikopter Service'),
       ('QGA', NULL, 'Windrose Air Jetcharter'),
       ('CWG', NULL, 'Wing Aviation'),
       ('WWP', 'WH', 'Wingo Panama'),
       ('WZZ', 'W6', 'Wizz Air'),
       ('WMT', 'W4', 'Wizz Air Malta'),
       ('CWY', NULL, 'Woodgate Aviation'),
       ('WCM', '3G', 'World Cargo Airlines'),
       ('WPT', '3P', 'World2Fly Portugal'),
       ('WRF', '8V', 'Wright Air Service'),
       ('XED', NULL, 'Xead Aviation'),
       ('CXA', 'MF', 'Xiamen Air'),
       ('XOJ', NULL, 'XO'),
       ('LLM', 'YC', 'Yamal Airlines'),
       ('DZD', NULL, 'Yazd Airways'),
       ('NYT', 'YT', 'Yeti Airlines'),
       ('TUD', NULL, 'Yute Commuter Services'),
       ('HMZ', NULL, 'Zafer Air'),
       ('AZB', 'ZN', 'Zambia Airways'),
       ('XEN', NULL, 'Zenflight'),
       ('ZAV', 'ZK', 'Zetavia'),
       ('JCN', NULL, 'Zhou Ji Airlines'),
       ('IMX', 'XM', 'Zimex Aviation'),
       ('TZP', 'ZG', 'Zipair'),
       ('ORZ', NULL, 'Zorex');

ALTER TABLE "public"."flight"
    ADD COLUMN "airline_id" INTEGER;

UPDATE "public"."flight" f
SET airline_id = a.id
FROM airline a
WHERE upper(trim(f.airline)) = a.icao
  AND f.airline_id IS NULL;

ALTER TABLE "public"."flight"
    ADD CONSTRAINT "flight_airline_id_fkey" FOREIGN KEY ("airline_id") REFERENCES "public"."airline" ("id") ON DELETE SET NULL ON UPDATE CASCADE;

ALTER TABLE "public"."flight"
    DROP COLUMN "airline";