name: Report a missing airport
description: Report a missing or unrecognized airport
body:
  - type: markdown
    attributes:
      value: |
        If you have found a missing airport, please report it directly to the [OurAirports](https://ourairports.com/) database. This is the source of the airport data used by AirTrail.

        If you have a different issue, please open a [bug report][bug] or [feature request][fr] instead.

        [bug]: https://github.com/johanohly/AirTrail/issues/new?template=bug_report.yml
        [fr]: https://github.com/JohanOhly/AirTrail/discussions/new?category=feature-request
