import { generateFiles } from "fumadocs-openapi";
import { openapi } from "@/lib/source";

const generatedPageMarker = "This file was generated by Fumadocs";
const apiPages = new Bun.Glob("content/docs/api/**/*.mdx");

for await (const path of apiPages.scan(".")) {
  const file = Bun.file(path);
  if ((await file.text()).includes(generatedPageMarker)) {
    await file.delete();
  }
}

await generateFiles({
  input: openapi,
  output: "./content/docs/api",
  groupBy: "tag",
  includeDescription: true,
});
