/**
 * Maya's travel history, the flights the demo and every screenshot are built
 * from. Home base is Copenhagen. The dates are written as if today were
 * `DEMO_NOW`: screenshots pin the browser clock to it, and a public demo moves
 * everything forward by whole weeks so the last trip was recent. The trips
 * after `DEMO_NOW` are upcoming.
 */

export const DEMO_NOW = new Date('2026-06-15T10:00:00Z');

export type Companion = 'jonas' | 'ella';

export type Leg = {
  /** Local departure date and time at the origin, `YYYY-MM-DD HH:mm`. */
  departs: string;
  from: string;
  to: string;
  flightNumber: string;
  airline: string;
  aircraft: string;
  registration?: string;
  seatClass?: 'economy' | 'economy+' | 'business' | 'first';
  seat?: 'window' | 'aisle' | 'middle';
  seatNumber?: string;
  /** Record a synthetic GPS track for this leg. */
  track?: boolean;
  note?: string;
  bookingReference?: string;
};

export type Trip = {
  reason: 'leisure' | 'business';
  with?: Companion[];
  legs: Leg[];
};

export const TRIPS: Trip[] = [
  {
    reason: 'leisure',
    legs: [
      {
        departs: '2019-02-14 07:05',
        from: 'CPH',
        to: 'LHR',
        flightNumber: 'BA811',
        airline: 'BAW',
        aircraft: 'A320',
        seat: 'window',
        seatNumber: '12A',
      },
      {
        departs: '2019-02-17 18:30',
        from: 'LHR',
        to: 'CPH',
        flightNumber: 'BA818',
        airline: 'BAW',
        aircraft: 'A320',
        seat: 'window',
        seatNumber: '14F',
      },
    ],
  },
  {
    reason: 'leisure',
    legs: [
      {
        departs: '2019-05-02 09:40',
        from: 'CPH',
        to: 'BCN',
        flightNumber: 'D83660',
        airline: 'NOZ',
        aircraft: 'B738',
        seat: 'aisle',
        seatNumber: '21C',
      },
      {
        departs: '2019-05-08 20:15',
        from: 'BCN',
        to: 'CPH',
        flightNumber: 'D83661',
        airline: 'NOZ',
        aircraft: 'B738',
        seat: 'aisle',
        seatNumber: '19D',
      },
    ],
  },
  {
    reason: 'leisure',
    with: ['jonas'],
    legs: [
      {
        departs: '2019-09-12 12:10',
        from: 'CPH',
        to: 'JFK',
        flightNumber: 'SK909',
        airline: 'SAS',
        aircraft: 'A333',
        registration: 'LN-RKR',
        seat: 'window',
        seatNumber: '32A',
        track: true,
        bookingReference: 'K7Q2LM',
      },
      {
        departs: '2019-09-22 17:35',
        from: 'JFK',
        to: 'CPH',
        flightNumber: 'SK910',
        airline: 'SAS',
        aircraft: 'A333',
        registration: 'SE-REF',
        seat: 'window',
        seatNumber: '30K',
        bookingReference: 'K7Q2LM',
      },
    ],
  },
  {
    reason: 'business',
    legs: [
      {
        departs: '2019-11-05 07:00',
        from: 'CPH',
        to: 'ARN',
        flightNumber: 'SK1417',
        airline: 'SAS',
        aircraft: 'CRJ9',
        seat: 'aisle',
        seatNumber: '3C',
      },
      {
        departs: '2019-11-06 19:05',
        from: 'ARN',
        to: 'CPH',
        flightNumber: 'SK1426',
        airline: 'SAS',
        aircraft: 'CRJ9',
        seat: 'aisle',
        seatNumber: '5D',
      },
    ],
  },
  {
    reason: 'business',
    legs: [
      {
        departs: '2020-02-03 08:20',
        from: 'CPH',
        to: 'HEL',
        flightNumber: 'AY952',
        airline: 'FIN',
        aircraft: 'A321',
        seat: 'aisle',
        seatNumber: '7C',
      },
      {
        departs: '2020-02-05 17:45',
        from: 'HEL',
        to: 'CPH',
        flightNumber: 'AY957',
        airline: 'FIN',
        aircraft: 'A321',
        seat: 'aisle',
        seatNumber: '9D',
      },
    ],
  },
  {
    reason: 'leisure',
    with: ['jonas'],
    legs: [
      {
        departs: '2021-08-01 06:45',
        from: 'CPH',
        to: 'ATH',
        flightNumber: 'SK775',
        airline: 'SAS',
        aircraft: 'A20N',
        seat: 'window',
        seatNumber: '18A',
        track: true,
      },
      {
        departs: '2021-08-15 12:30',
        from: 'ATH',
        to: 'CPH',
        flightNumber: 'SK776',
        airline: 'SAS',
        aircraft: 'A20N',
        seat: 'window',
        seatNumber: '16F',
      },
    ],
  },
  {
    reason: 'leisure',
    with: ['jonas'],
    legs: [
      {
        departs: '2022-03-10 13:20',
        from: 'CPH',
        to: 'KEF',
        flightNumber: 'FI205',
        airline: 'ICE',
        aircraft: 'B38M',
        seat: 'window',
        seatNumber: '11A',
        note: 'Northern lights on the approach.',
      },
      {
        departs: '2022-03-14 07:40',
        from: 'KEF',
        to: 'CPH',
        flightNumber: 'FI204',
        airline: 'ICE',
        aircraft: 'B38M',
        seat: 'window',
        seatNumber: '12F',
      },
    ],
  },
  {
    reason: 'business',
    legs: [
      {
        departs: '2022-05-19 06:55',
        from: 'CPH',
        to: 'AMS',
        flightNumber: 'KL1124',
        airline: 'KLM',
        aircraft: 'E195',
        seat: 'aisle',
        seatNumber: '6C',
      },
      {
        departs: '2022-05-20 18:10',
        from: 'AMS',
        to: 'CPH',
        flightNumber: 'KL1135',
        airline: 'KLM',
        aircraft: 'E195',
        seat: 'aisle',
        seatNumber: '8D',
      },
    ],
  },
  {
    reason: 'leisure',
    legs: [
      {
        departs: '2022-10-20 15:15',
        from: 'CPH',
        to: 'DXB',
        flightNumber: 'EK152',
        airline: 'UAE',
        aircraft: 'A388',
        registration: 'A6-EOT',
        seat: 'window',
        seatNumber: '44A',
        track: true,
        bookingReference: 'EKX9TT',
      },
      {
        departs: '2022-10-21 03:30',
        from: 'DXB',
        to: 'SIN',
        flightNumber: 'EK354',
        airline: 'UAE',
        aircraft: 'B77W',
        seat: 'window',
        seatNumber: '38K',
        bookingReference: 'EKX9TT',
      },
      {
        departs: '2022-11-05 23:55',
        from: 'SIN',
        to: 'CPH',
        flightNumber: 'SQ352',
        airline: 'SIA',
        aircraft: 'A359',
        seatClass: 'economy+',
        seat: 'aisle',
        seatNumber: '31C',
        track: true,
      },
    ],
  },
  {
    reason: 'business',
    legs: [
      {
        departs: '2022-12-01 07:10',
        from: 'CPH',
        to: 'FRA',
        flightNumber: 'LH827',
        airline: 'DLH',
        aircraft: 'A320',
        seat: 'aisle',
        seatNumber: '4C',
      },
      {
        departs: '2022-12-02 19:40',
        from: 'FRA',
        to: 'CPH',
        flightNumber: 'LH830',
        airline: 'DLH',
        aircraft: 'A320',
        seat: 'aisle',
        seatNumber: '5D',
      },
    ],
  },
  {
    reason: 'leisure',
    legs: [
      {
        departs: '2023-04-06 10:05',
        from: 'CPH',
        to: 'LIS',
        flightNumber: 'TP755',
        airline: 'TAP',
        aircraft: 'A321',
        seat: 'window',
        seatNumber: '22A',
      },
      {
        departs: '2023-04-12 06:25',
        from: 'LIS',
        to: 'CPH',
        flightNumber: 'TP754',
        airline: 'TAP',
        aircraft: 'A321',
        seat: 'window',
        seatNumber: '24F',
      },
    ],
  },
  {
    reason: 'leisure',
    with: ['jonas'],
    legs: [
      {
        departs: '2023-06-20 11:50',
        from: 'CPH',
        to: 'EWR',
        flightNumber: 'SK911',
        airline: 'SAS',
        aircraft: 'A359',
        registration: 'SE-RSA',
        seatClass: 'economy+',
        seat: 'window',
        seatNumber: '28A',
        track: true,
        bookingReference: 'SK4RW8',
      },
      {
        departs: '2023-06-24 08:15',
        from: 'EWR',
        to: 'SFO',
        flightNumber: 'UA1181',
        airline: 'UAL',
        aircraft: 'B789',
        seat: 'window',
        seatNumber: '24A',
        track: true,
      },
      {
        departs: '2023-07-02 14:05',
        from: 'SFO',
        to: 'CPH',
        flightNumber: 'SK936',
        airline: 'SAS',
        aircraft: 'A359',
        registration: 'SE-RSC',
        seatClass: 'economy+',
        seat: 'window',
        seatNumber: '27K',
        bookingReference: 'SK4RW8',
      },
    ],
  },
  {
    reason: 'business',
    legs: [
      {
        departs: '2023-09-14 07:25',
        from: 'CPH',
        to: 'OSL',
        flightNumber: 'SK1456',
        airline: 'SAS',
        aircraft: 'A20N',
        seat: 'aisle',
        seatNumber: '2C',
      },
      {
        departs: '2023-09-15 17:55',
        from: 'OSL',
        to: 'CPH',
        flightNumber: 'SK1469',
        airline: 'SAS',
        aircraft: 'A20N',
        seat: 'aisle',
        seatNumber: '3D',
      },
    ],
  },
  {
    reason: 'leisure',
    legs: [
      {
        departs: '2023-12-20 09:30',
        from: 'CPH',
        to: 'ZRH',
        flightNumber: 'LX1263',
        airline: 'SWR',
        aircraft: 'A20N',
        seat: 'window',
        seatNumber: '15A',
        note: 'Ski week in Laax.',
      },
      {
        departs: '2023-12-28 16:10',
        from: 'ZRH',
        to: 'CPH',
        flightNumber: 'LX1268',
        airline: 'SWR',
        aircraft: 'A20N',
        seat: 'window',
        seatNumber: '17F',
      },
    ],
  },
  {
    reason: 'leisure',
    with: ['jonas', 'ella'],
    legs: [
      {
        departs: '2024-03-28 07:30',
        from: 'CPH',
        to: 'HEL',
        flightNumber: 'AY952',
        airline: 'FIN',
        aircraft: 'A321',
        seat: 'window',
        seatNumber: '10A',
      },
      {
        departs: '2024-03-28 17:20',
        from: 'HEL',
        to: 'HND',
        flightNumber: 'AY61',
        airline: 'FIN',
        aircraft: 'A359',
        registration: 'OH-LWL',
        seat: 'window',
        seatNumber: '40A',
        track: true,
        bookingReference: 'AYJP24',
      },
      {
        departs: '2024-04-12 11:40',
        from: 'HND',
        to: 'HEL',
        flightNumber: 'AY62',
        airline: 'FIN',
        aircraft: 'A359',
        seat: 'window',
        seatNumber: '41K',
        bookingReference: 'AYJP24',
      },
      {
        departs: '2024-04-13 08:10',
        from: 'HEL',
        to: 'CPH',
        flightNumber: 'AY951',
        airline: 'FIN',
        aircraft: 'A321',
        seat: 'window',
        seatNumber: '11F',
      },
    ],
  },
  {
    reason: 'leisure',
    legs: [
      {
        departs: '2024-05-30 06:35',
        from: 'CPH',
        to: 'DUB',
        flightNumber: 'FR3301',
        airline: 'RYR',
        aircraft: 'B738',
        seat: 'middle',
        seatNumber: '17B',
      },
      {
        departs: '2024-06-02 21:05',
        from: 'DUB',
        to: 'CPH',
        flightNumber: 'FR3302',
        airline: 'RYR',
        aircraft: 'B738',
        seat: 'aisle',
        seatNumber: '9C',
      },
    ],
  },
  {
    reason: 'leisure',
    legs: [
      {
        departs: '2024-09-05 10:20',
        from: 'CPH',
        to: 'CDG',
        flightNumber: 'AF1751',
        airline: 'AFR',
        aircraft: 'A320',
        seat: 'window',
        seatNumber: '19A',
      },
      {
        departs: '2024-09-08 19:35',
        from: 'CDG',
        to: 'CPH',
        flightNumber: 'AF1750',
        airline: 'AFR',
        aircraft: 'A320',
        seat: 'window',
        seatNumber: '21F',
      },
    ],
  },
  {
    reason: 'business',
    legs: [
      {
        departs: '2024-10-17 11:15',
        from: 'CPH',
        to: 'IST',
        flightNumber: 'TK1784',
        airline: 'THY',
        aircraft: 'A321',
        seat: 'aisle',
        seatNumber: '14C',
      },
      {
        departs: '2024-10-21 08:05',
        from: 'IST',
        to: 'CPH',
        flightNumber: 'TK1783',
        airline: 'THY',
        aircraft: 'A321',
        seat: 'aisle',
        seatNumber: '12D',
      },
    ],
  },
  {
    reason: 'business',
    legs: [
      {
        departs: '2024-11-20 07:00',
        from: 'CPH',
        to: 'ARN',
        flightNumber: 'SK1417',
        airline: 'SAS',
        aircraft: 'A20N',
        seat: 'aisle',
        seatNumber: '4C',
      },
      {
        departs: '2024-11-21 18:20',
        from: 'ARN',
        to: 'CPH',
        flightNumber: 'SK1424',
        airline: 'SAS',
        aircraft: 'A20N',
        seat: 'aisle',
        seatNumber: '6D',
      },
    ],
  },
  {
    reason: 'leisure',
    legs: [
      {
        departs: '2025-02-10 13:30',
        from: 'CPH',
        to: 'KEF',
        flightNumber: 'FI205',
        airline: 'ICE',
        aircraft: 'B38M',
        seat: 'window',
        seatNumber: '14A',
      },
      {
        departs: '2025-02-10 17:00',
        from: 'KEF',
        to: 'YYZ',
        flightNumber: 'FI603',
        airline: 'ICE',
        aircraft: 'B763',
        seat: 'window',
        seatNumber: '26A',
        track: true,
      },
      {
        departs: '2025-02-18 20:20',
        from: 'YYZ',
        to: 'KEF',
        flightNumber: 'FI602',
        airline: 'ICE',
        aircraft: 'B763',
        seat: 'window',
        seatNumber: '25K',
      },
      {
        departs: '2025-02-19 07:40',
        from: 'KEF',
        to: 'CPH',
        flightNumber: 'FI204',
        airline: 'ICE',
        aircraft: 'B38M',
        seat: 'window',
        seatNumber: '13F',
      },
    ],
  },
  {
    reason: 'leisure',
    legs: [
      {
        departs: '2025-04-17 09:55',
        from: 'CPH',
        to: 'FCO',
        flightNumber: 'SK683',
        airline: 'SAS',
        aircraft: 'A20N',
        seat: 'window',
        seatNumber: '20A',
      },
      {
        departs: '2025-04-22 13:40',
        from: 'FCO',
        to: 'CPH',
        flightNumber: 'SK684',
        airline: 'SAS',
        aircraft: 'A20N',
        seat: 'window',
        seatNumber: '18F',
      },
    ],
  },
  {
    reason: 'leisure',
    legs: [
      {
        departs: '2025-06-06 16:45',
        from: 'CPH',
        to: 'BER',
        flightNumber: 'U28116',
        airline: 'EZY',
        aircraft: 'A20N',
        seat: 'aisle',
        seatNumber: '6C',
      },
      {
        departs: '2025-06-08 20:30',
        from: 'BER',
        to: 'CPH',
        flightNumber: 'U28117',
        airline: 'EZY',
        aircraft: 'A20N',
        seat: 'aisle',
        seatNumber: '7D',
      },
    ],
  },
  {
    reason: 'leisure',
    with: ['jonas'],
    legs: [
      {
        departs: '2025-11-02 16:05',
        from: 'CPH',
        to: 'DOH',
        flightNumber: 'QR160',
        airline: 'QTR',
        aircraft: 'B789',
        seatClass: 'business',
        seat: 'window',
        seatNumber: '3A',
        track: true,
        bookingReference: 'QRMV25',
      },
      {
        departs: '2025-11-03 02:15',
        from: 'DOH',
        to: 'MLE',
        flightNumber: 'QR672',
        airline: 'QTR',
        aircraft: 'A359',
        seatClass: 'business',
        seat: 'window',
        seatNumber: '2A',
        bookingReference: 'QRMV25',
      },
      {
        departs: '2025-11-14 21:30',
        from: 'MLE',
        to: 'DOH',
        flightNumber: 'QR673',
        airline: 'QTR',
        aircraft: 'A359',
        seatClass: 'business',
        seat: 'window',
        seatNumber: '2K',
        bookingReference: 'QRMV25',
      },
      {
        departs: '2025-11-15 07:55',
        from: 'DOH',
        to: 'CPH',
        flightNumber: 'QR159',
        airline: 'QTR',
        aircraft: 'B789',
        seatClass: 'business',
        seat: 'window',
        seatNumber: '4K',
        bookingReference: 'QRMV25',
      },
    ],
  },
  {
    reason: 'leisure',
    legs: [
      {
        departs: '2025-12-11 07:05',
        from: 'CPH',
        to: 'LHR',
        flightNumber: 'BA811',
        airline: 'BAW',
        aircraft: 'A320',
        seat: 'window',
        seatNumber: '11A',
      },
      {
        departs: '2025-12-14 18:30',
        from: 'LHR',
        to: 'CPH',
        flightNumber: 'BA818',
        airline: 'BAW',
        aircraft: 'A320',
        seat: 'window',
        seatNumber: '13F',
      },
    ],
  },
  {
    reason: 'business',
    legs: [
      {
        departs: '2026-01-22 06:55',
        from: 'CPH',
        to: 'AMS',
        flightNumber: 'KL1124',
        airline: 'KLM',
        aircraft: 'E195',
        seat: 'aisle',
        seatNumber: '5C',
      },
      {
        departs: '2026-01-23 18:10',
        from: 'AMS',
        to: 'CPH',
        flightNumber: 'KL1135',
        airline: 'KLM',
        aircraft: 'E195',
        seat: 'aisle',
        seatNumber: '7D',
      },
    ],
  },
  {
    reason: 'leisure',
    legs: [
      {
        departs: '2026-03-19 10:35',
        from: 'CPH',
        to: 'MAD',
        flightNumber: 'IB3281',
        airline: 'IBE',
        aircraft: 'A321',
        seat: 'window',
        seatNumber: '23A',
      },
      {
        departs: '2026-03-24 15:20',
        from: 'MAD',
        to: 'CPH',
        flightNumber: 'IB3282',
        airline: 'IBE',
        aircraft: 'A321',
        seat: 'window',
        seatNumber: '25F',
      },
    ],
  },
  {
    reason: 'leisure',
    with: ['jonas', 'ella'],
    legs: [
      {
        departs: '2026-05-28 08:15',
        from: 'CPH',
        to: 'SPU',
        flightNumber: 'D83550',
        airline: 'NOZ',
        aircraft: 'B38M',
        seat: 'window',
        seatNumber: '15A',
        track: true,
      },
      {
        departs: '2026-06-04 12:45',
        from: 'SPU',
        to: 'CPH',
        flightNumber: 'D83551',
        airline: 'NOZ',
        aircraft: 'B38M',
        seat: 'window',
        seatNumber: '16F',
      },
    ],
  },
  {
    reason: 'business',
    legs: [
      {
        departs: '2026-07-02 07:05',
        from: 'CPH',
        to: 'LHR',
        flightNumber: 'BA811',
        airline: 'BAW',
        aircraft: 'A320',
        seatClass: 'economy+',
        seat: 'aisle',
        seatNumber: '8C',
        bookingReference: 'QK7M2P',
      },
      {
        departs: '2026-07-03 18:30',
        from: 'LHR',
        to: 'CPH',
        flightNumber: 'BA818',
        airline: 'BAW',
        aircraft: 'A320',
        seatClass: 'economy+',
        seat: 'aisle',
        seatNumber: '9D',
        bookingReference: 'QK7M2P',
      },
    ],
  },
  {
    reason: 'leisure',
    with: ['jonas'],
    legs: [
      {
        departs: '2026-08-14 09:40',
        from: 'CPH',
        to: 'HEL',
        flightNumber: 'AY952',
        airline: 'FIN',
        aircraft: 'A321',
        seat: 'window',
        seatNumber: '14A',
        note: 'Summer cabin by the lake.',
      },
    ],
  },
];

/** Visited-country entries beyond what the flights imply. */
export const EXTRA_COUNTRIES: {
  code: string;
  status: 'lived' | 'visited' | 'layover' | 'wishlist';
  note?: string;
}[] = [
  { code: 'DK', status: 'lived', note: 'Home.' },
  { code: 'DE', status: 'lived', note: 'Two years in Hamburg.' },
  { code: 'NO', status: 'visited' },
  { code: 'JP', status: 'visited' },
  { code: 'NZ', status: 'wishlist' },
  { code: 'PE', status: 'wishlist' },
  { code: 'CL', status: 'wishlist' },
];
