CREATE TABLE airport_new (
  id         INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  icao       TEXT    NOT NULL,
  iata       TEXT,
  lat        DOUBLE PRECISION NOT NULL,
  lon        DOUBLE PRECISION NOT NULL,
  tz         TEXT    NOT NULL,
  name       TEXT    NOT NULL,
  type       TEXT    NOT NULL,
  continent  TEXT    NOT NULL,
  country    TEXT    NOT NULL,
  custom     BOOLEAN NOT NULL DEFAULT FALSE
);

INSERT INTO airport_new (icao, iata, lat, lon, tz, name, type, continent, country, custom)
SELECT code, iata, lat, lon, tz, name, type, continent, country, custom
FROM airport;

ALTER TABLE flight
  ADD COLUMN from_id INTEGER,
  ADD COLUMN to_id   INTEGER;

UPDATE flight f
SET from_id = a.id
FROM airport_new a
WHERE f."from" = a.icao;

UPDATE flight f
SET to_id = a.id
FROM airport_new a
WHERE f."to" = a.icao;

ALTER TABLE flight
  DROP COLUMN "from",
  DROP COLUMN "to";

DROP TABLE airport;
ALTER TABLE airport_new RENAME TO airport;

ALTER TABLE "public"."airport" RENAME CONSTRAINT "airport_new_pkey" TO "airport_pkey";

ALTER TABLE flight
  ADD CONSTRAINT flight_from_id_fkey
    FOREIGN KEY (from_id) REFERENCES airport(id) ON UPDATE CASCADE ON DELETE SET NULL,
  ADD CONSTRAINT flight_to_id_fkey
    FOREIGN KEY (to_id)   REFERENCES airport(id) ON UPDATE CASCADE ON DELETE SET NULL;

CREATE INDEX flight_from_id_idx ON flight(from_id);
CREATE INDEX flight_to_id_idx   ON flight(to_id);